"SYNTAX for BEYOND ZORK:
 Copyright (C)1987 Infocom, Inc. All Rights Reserved."

<BUZZ A AN THE ARE AM ; PM AND OF THEN ALL BOTH EVERYTHING BUT
      EXCEPT \. \, \" \? \! 
      ; PRY HERE SOME SO PLEASE>

<BUZZ CAREFULLY CLOSELY SLOWLY QUICKLY RAPIDLY QUIETLY>

<BUZZ MR MRS MISS>

<BUZZ WHY HOW WHEN WOULD COULD SHOULD HAS AM IS WAS>

<BUZZ ZERO ONE TWO THREE ; FOUR FIVE ; SIX SEVEN EIGHT NINE TEN>

<BUZZ FUCK FUCKED CURSE GODDAMNED CUSS DAMN SHIT CRAP ASSHOLE ASS CUNT 
      SHITHEAD PISS BASTARD FUCKING DAMNED PEE COCKSUCKER BITCH>

<BUZZ XYZZY PLUGH PLOVER YOHO ULYSSES ODYSSEUS>

<VOC "SECRET" ADJ>
<VOC "DEAD" ADJ>
<VOC "SLEEPING" ADJ>
<VOC "BEGIN" NOUN>
<VOC "B" NOUN>
<VOC "CLOSED" ADJ>
<VOC "LIGHTED" ADJ>

<PREP-SYNONYM TO TOWARD TOWARDS>
<PREP-SYNONYM WITH USING>
<PREP-SYNONYM THROUGH THRU>
<PREP-SYNONYM ON ONTO ABOARD UPON>
<PREP-SYNONYM IN INSIDE INTO BETWEEN WITHIN>
<PREP-SYNONYM OUT OUTSIDE>
<PREP-SYNONYM UNDER BELOW BENEATH UNDERNEATH>
<PREP-SYNONYM AROUND ALONG>
<PREP-SYNONYM OVER ACROSS>
<PREP-SYNONYM BEHIND BEYOND>
<PREP-SYNONYM AGAINST NEAR>

; <SYNONYM ALL BOTH EVERYTHING>

<SYNONYM NORTH N>
<SYNONYM SOUTH S>
<SYNONYM EAST E>
<SYNONYM WEST W>
<SYNONYM NE NORTHEAST>
<SYNONYM NW NORTHWEST>
<SYNONYM SE SOUTHEAST>
<SYNONYM SW SOUTHWEST>
<SYNONYM DOWN D>
<SYNONYM UP U>

<SYNTAX VERBOSE = V-VERBOSE>
<SYNTAX BRIEF = V-BRIEF>
<SYNTAX SUPER = V-SUPER-BRIEF>
<VERB-SYNONYM SUPER SUPERBRIEF>

<SYNTAX MODE = V-MODE>
<SYNTAX DEFINE = V-DEFINE>

<SYNTAX PRIORITY OBJECT (FIND LOCATION) = V-PRIORITY-ON>
<SYNTAX PRIORITY ON OBJECT (FIND LOCATION) = V-PRIORITY-ON>
<SYNTAX PRIORITY OFF OBJECT (FIND LOCATION) = V-PRIORITY-OFF>

<SYNTAX ZOOM OBJECT (FIND LOCATION) = V-ZOOM>

<SYNTAX CASH = V-CASH>
<VERB-SYNONYM CASH $>

<SYNTAX I = V-INVENTORY>
<VERB-SYNONYM I INVENTORY>

<SYNTAX STATUS = V-STATUS>
<VERB-SYNONYM STATUS STATS STAT>

<SYNTAX DIAGNOSE OBJECT (FIND LOCATION) = V-DIAGNOSE>

<SYNTAX SETTINGS = V-SETTINGS>
<SYNTAX REFRESH = V-REFRESH>
<SYNTAX MONITOR = V-MONITOR>

<SYNTAX QUIT = V-QUIT>
<VERB-SYNONYM QUIT Q>

<SYNTAX RESTART = V-RESTART>

<SYNTAX SAVE = V-SAVE>
<SYNTAX SAVE OBJECT = V-RESCUE>
<SYNTAX RESTORE = V-RESTORE>

<SYNTAX UNDO = V-UNDO>

<SYNTAX SCORE = V-SCORE>

<SYNTAX TIME = V-TIME>
<VERB-SYNONYM TIME T>

<SYNTAX SCRIPT = V-SCRIPT>
<SYNTAX UNSCRIPT = V-UNSCRIPT>

<SYNTAX VERSION = V-VERSION>

<SYNTAX $VERIFY = V-$VERIFY>
; <SYNTAX $VERIFY OBJECT = V-$VERIFY>
<VERB-SYNONYM $VERIFY $VER>

<SYNTAX COLOR OBJECT (FIND LOCATION) = V-COLOR>
<VERB-SYNONYM COLOR COLORS>

<SYNTAX NOTIFY = V-NOTIFY>

; <SYNTAX \#RECORD = V-$RECORD>
; <SYNTAX \#UNRECORD = V-$UNRECORD>
; <SYNTAX \#RANDOM OBJECT = V-$RANDOM>
; <SYNTAX \#COMMAND = V-$COMMAND>

<SYNTAX ANSWER OBJECT (FIND PERSON) = V-REPLY>

<SYNTAX REPLY TO OBJECT (FIND PERSON) = V-REPLY>
<VERB-SYNONYM REPLY RESPOND>

<SYNTAX APPLY OBJECT (HAVE HELD MANY) ON OBJECT = V-PUT PRE-PUT>
<SYNTAX APPLY OBJECT (HAVE HELD MANY) TO OBJECT = V-PUT PRE-PUT>

<SYNTAX ASK OBJECT (FIND PERSON) = V-QUESTION>
<SYNTAX ASK ABOUT OBJECT (FIND PERSON) = V-QUESTION>
<SYNTAX ASK FOR OBJECT = V-REQUEST>
<SYNTAX ASK OBJECT (FIND PERSON) ABOUT OBJECT = V-ASK-ABOUT>
<SYNTAX ASK OBJECT (FIND PERSON) FOR OBJECT = V-ASK-FOR>

<SYNTAX REQUEST OBJECT = V-REQUEST>
<SYNTAX REQUEST OBJECT FROM OBJECT (FIND PERSON) = V-SASK-FOR>

<SYNTAX SPEND OBJECT (FIND LOCATION) = V-SPEND>
<SYNTAX SPEND OBJECT (HELD CARRIED HAVE) ON OBJECT = V-SBUY>
<VERB-SYNONYM SPEND WASTE>

<SYNTAX BUY OBJECT = V-BUY PRE-BUY>
<SYNTAX BUY OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-BUY PRE-BUY>
<SYNTAX BUY OBJECT FOR OBJECT (HELD CARRIED HAVE) = V-BUY PRE-BUY>
<SYNTAX BUY OBJECT FROM OBJECT = V-BUY-FROM>
<VERB-SYNONYM BUY PURCHASE>

<SYNTAX TRADE OBJECT (HELD CARRIED HAVE) FOR OBJECT 
	= V-TRADE-FOR PRE-TRADE-FOR>
<SYNTAX TRADE FOR OBJECT = V-REQUEST>
<VERB-SYNONYM TRADE EXCHANGE BARTER>

<SYNTAX PAY OBJECT = V-PAY>
<SYNTAX PAY OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-PAY>
<SYNTAX PAY FOR OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-SBUY>

<SYNTAX BRIBE OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-PAY>

<SYNTAX OFFER OBJECT (HELD CARRIED HAVE ; TAKE)
        TO OBJECT (IN-ROOM ON-GROUND) = V-GIVE PRE-GIVE>
<SYNTAX OFFER OBJECT (ON-GROUND IN-ROOM)
	OBJECT (HELD CARRIED HAVE ; TAKE) = V-SGIVE>
<SYNTAX OFFER OBJECT (HELD CARRIED HAVE) FOR OBJECT 
	= V-TRADE-FOR PRE-TRADE-FOR>


<SYNTAX SELL OBJECT (HELD CARRIED ; HAVE)
	= V-SELL-TO PRE-SELL-TO>
<SYNTAX SELL OBJECT (HELD CARRIED ; HAVE)
	TO OBJECT (ON-GROUND IN-ROOM) = V-SELL-TO PRE-SELL-TO>
<SYNTAX SELL OBJECT (ON-GROUND IN-ROOM)
	OBJECT (HELD CARRIED ; HAVE ; TAKE) = V-SSELL-TO>
<SYNTAX SELL OBJECT (HELD CARRIED HAVE) FOR OBJECT 
	= V-TRADE-FOR PRE-TRADE-FOR>

<SYNTAX QUESTION OBJECT (FIND PERSON) = V-QUESTION>
<SYNTAX QUESTION OBJECT (FIND PERSON) ABOUT OBJECT = V-ASK-ABOUT>
<VERB-SYNONYM QUESTION QUIZ INTERROGATE QUERY>

<SYNTAX BACK = V-WALK-AROUND>
<SYNTAX BACK AWAY OBJECT (FIND LOCATION) = V-ESCAPE>

<SYNTAX CIRCLE OBJECT (FIND LOCATION) = V-WALK-AROUND>

<SYNTAX RETREAT = V-WALK-AROUND>
<SYNTAX RETREAT FROM OBJECT = V-ESCAPE>
<SYNTAX RETREAT AWAY OBJECT (FIND LOCATION) = V-ESCAPE>

<SYNTAX BITE OBJECT = V-BITE>

<SYNTAX BLOW OBJECT = V-BLOW-INTO>
<SYNTAX BLOW IN OBJECT = V-BLOW-INTO>
<SYNTAX BLOW ON OBJECT = V-BLOW-INTO>
<SYNTAX BLOW THROUGH OBJECT = V-BLOW-INTO>
<SYNTAX BLOW UP OBJECT = V-DETONATE>
<SYNTAX BLOW OUT OBJECT = V-LAMP-OFF>

<SYNTAX BURN OBJECT (HELD CARRIED ON-GROUND IN-ROOM)
        WITH OBJECT (HELD CARRIED HAVE) = V-BURN-WITH>
<SYNTAX BURN DOWN OBJECT (HELD CARRIED ON-GROUND IN-ROOM)
	WITH OBJECT (HELD CARRIED HAVE) = V-BURN-WITH>
<SYNTAX BURN UP OBJECT (HELD CARRIED ON-GROUND IN-ROOM)
	WITH OBJECT (HELD CARRIED HAVE) = V-BURN-WITH>
<VERB-SYNONYM BURN KINDLE COMBUST SCORCH IGNITE CHAR INCINERAT CREMATE>

<SYNTAX CLEAN OBJECT = V-CLEAN>
<SYNTAX CLEAN OFF OBJECT = V-CLEAN>
<SYNTAX CLEAN OBJECT (HELD CARRIED HAVE) ON OBJECT = V-CLEAN-OFF>
<SYNTAX CLEAN OBJECT (HELD CARRIED HAVE) OFF OBJECT = V-CLEAN-OFF>
<SYNTAX CLEAN OFF OBJECT (HELD CARRIED HAVE) ON OBJECT = V-CLEAN-OFF>
<SYNTAX CLEAN OBJECT (HELD CARRIED HAVE) OVER OBJECT = V-CLEAN-OFF>
<SYNTAX CLEAN OFF OBJECT (HELD CARRIED HAVE) OVER OBJECT = V-CLEAN-OFF>
<VERB-SYNONYM CLEAN SWEEP WIPE POLISH>

<SYNTAX CLIMB OBJECT (FIND LOCATION) (ON-GROUND IN-ROOM) = V-CLIMB-UP>
<SYNTAX CLIMB ON OBJECT (ON-GROUND IN-ROOM) = V-CLIMB-ON>
<SYNTAX CLIMB UP OBJECT (FIND LOCATION) (ON-GROUND IN-ROOM) = V-CLIMB-UP>
<SYNTAX CLIMB DOWN OBJECT (FIND LOCATION) (ON-GROUND IN-ROOM) = V-CLIMB-DOWN>
<SYNTAX CLIMB OVER OBJECT (FIND LOCATION) (ON-GROUND IN-ROOM) = V-CLIMB-OVER>
<SYNTAX CLIMB UNDER OBJECT (ON-GROUND IN-ROOM) = V-STAND-UNDER>
<SYNTAX CLIMB IN OBJECT (FIND LOCATION) (ON-GROUND IN-ROOM) = V-ENTER>
<SYNTAX CLIMB THROUGH OBJECT (ON-GROUND IN-ROOM) = V-THROUGH>
<SYNTAX CLIMB OUT OBJECT (FIND LOCATION) = V-EXIT>
<VERB-SYNONYM CLIMB CLAMBER>

<SYNTAX SCALE OBJECT (FIND LOCATION) (ON-GROUND IN-ROOM) = V-CLIMB-UP>
<SYNTAX SCALE UP OBJECT (FIND LOCATION) (ON-GROUND IN-ROOM) = V-CLIMB-UP> 
<SYNTAX SCALE DOWN OBJECT (FIND LOCATION) (ON-GROUND IN-ROOM)
	= V-CLIMB-DOWN>
<SYNTAX SCALE OVER OBJECT (FIND LOCATION) (ON-GROUND IN-ROOM) 
	= V-CLIMB-OVER>
<SYNTAX ASCEND OBJECT (FIND LOCATION) (ON-GROUND IN-ROOM) 
	= V-CLIMB-UP>

<SYNTAX DESCEND OBJECT (FIND LOCATION) (ON-GROUND IN-ROOM) = V-CLIMB-DOWN>

<SYNTAX CLOSE OBJECT (FIND OPENED) (HELD CARRIED ON-GROUND IN-ROOM)
        = V-CLOSE>
<SYNTAX CLOSE OFF OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-LAMP-OFF>
<VERB-SYNONYM CLOSE SHUT SLAM>

<SYNTAX COUNT OBJECT = V-COUNT>
<VERB-SYNONYM COUNT TALLY>

<SYNTAX CROSS OBJECT = V-CROSS>
<SYNTAX CROSS OVER OBJECT = V-CROSS>
<VERB-SYNONYM CROSS TRAVERSE>

<SYNTAX CUT OBJECT WITH OBJECT (FIND TOOL) (CARRIED HELD HAVE ; TAKE) 
	= V-CUT>
<SYNTAX CUT UP OBJECT WITH OBJECT (FIND TOOL) (CARRIED HELD HAVE ; TAKE)
        = V-CUT>
<SYNTAX CUT THROUGH OBJECT WITH OBJECT (FIND TOOL) 
	(HELD CARRIED HAVE ; TAKE) = V-CUT>
<SYNTAX CUT DOWN OBJECT WITH OBJECT (FIND TOOL) (CARRIED HELD HAVE ; TAKE)
	= V-CUT>
<VERB-SYNONYM CUT CHOP SLASH SLICE GASH ; LACERATE CLEAVE SEVER SPLIT> 

<SYNTAX RIP OBJECT WITH OBJECT (FIND MANUALLY) (CARRIED HELD HAVE ; TAKE) 
	= V-RIP>
<SYNTAX RIP UP OBJECT WITH OBJECT (FIND MANUALLY) (CARRIED HELD HAVE ; TAKE)
        = V-RIP>
<SYNTAX RIP THROUGH OBJECT WITH OBJECT (FIND MANUALLY) 
	(HELD CARRIED HAVE ; TAKE) = V-RIP>
<SYNTAX RIP DOWN OBJECT WITH OBJECT (FIND MANUALLY) (CARRIED HELD HAVE ; TAKE)
	= V-RIP>
<SYNTAX RIP OFF OBJECT (FIND TAKEABLE) = V-TAKE PRE-TAKE>
<VERB-SYNONYM RIP TEAR>

<SYNTAX FELL OBJECT WITH OBJECT (FIND TOOL) (CARRIED HELD HAVE ; TAKE) 
	= V-CUT>

<SYNTAX BREAK OBJECT (ON-GROUND IN-ROOM HELD CARRIED)
	WITH OBJECT (FIND MANUALLY) (HAVE HELD CARRIED) = V-MUNG>
<SYNTAX BREAK OBJECT (ON-GROUND IN-ROOM)
	OFF OBJECT (ON-GROUND IN-ROOM) = V-MUNG>
<SYNTAX BREAK DOWN OBJECT (ON-GROUND IN-ROOM HELD CARRIED)
	WITH OBJECT (FIND MANUALLY) (HAVE HELD CARRIED) = V-MUNG>
<SYNTAX BREAK IN OBJECT (ON-GROUND IN-ROOM) 
	WITH OBJECT (FIND MANUALLY) (HAVE HELD CARRIED) = V-MUNG>
<SYNTAX BREAK THROUGH OBJECT (ON-GROUND IN-ROOM)
	WITH OBJECT (FIND MANUALLY) (HAVE HELD CARRIED) = V-MUNG>
<VERB-SYNONYM BREAK DESTROY DAMAGE SMASH DEMOLISH WRECK CRACK ; TRASH CRUMBLE>

<SYNTAX DIG IN OBJECT (ON-GROUND IN-ROOM) = V-DIG PRE-DIG>
<SYNTAX DIG IN OBJECT (ON-GROUND IN-ROOM)
	WITH OBJECT (HELD CARRIED HAVE) = V-DIG PRE-DIG>
<SYNTAX DIG AT OBJECT (ON-GROUND IN-ROOM) = V-DIG PRE-DIG>
<SYNTAX DIG AT OBJECT (ON-GROUND IN-ROOM)
	WITH OBJECT (HELD CARRIED HAVE) = V-DIG PRE-DIG>
<SYNTAX DIG UP OBJECT (ON-GROUND IN-ROOM) = V-DIG PRE-DIG>
<SYNTAX DIG UP OBJECT (ON-GROUND IN-ROOM)
	WITH OBJECT (HELD CARRIED HAVE) = V-DIG PRE-DIG>
<SYNTAX DIG UNDER OBJECT (ON-GROUND IN-ROOM) = V-DIG PRE-DIG>
<SYNTAX DIG UNDER OBJECT (ON-GROUND IN-ROOM)
	WITH OBJECT (HELD CARRIED HAVE) = V-DIG-UNDER PRE-DIG-UNDER>
<SYNTAX DIG WITH OBJECT (HELD CARRIED HAVE) IN OBJECT (ON-GROUND IN-ROOM)
	= V-SDIG>
<SYNTAX DIG THROUGH OBJECT (ON-GROUND IN-ROOM) = V-SEARCH>
<SYNTAX DIG THROUGH OBJECT (ON-GROUND IN-ROOM)
	WITH OBJECT (HELD CARRIED HAVE) = V-DIG PRE-DIG>
<SYNTAX DIG OBJECT (ON-GROUND IN-ROOM) = V-DIG PRE-DIG>
<SYNTAX DIG OBJECT (ON-GROUND IN-ROOM)
	WITH OBJECT (HELD CARRIED HAVE) = V-DIG PRE-DIG>
; <VERB-SYNONYM DIG EXCAVATE>

<SYNTAX DRINK OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-DRINK>
<SYNTAX DRINK FROM OBJECT (HELD CARRIED) = V-DRINK-FROM>
<VERB-SYNONYM DRINK SIP GUZZLE IMBIBE QUAFF SWILL>

<SYNTAX DROP OBJECT (HELD MANY HAVE) = V-DROP>
<SYNTAX DROP OBJECT (HELD MANY HAVE) DOWN OBJECT = V-PUT PRE-PUT>
<SYNTAX DROP OBJECT (HELD MANY HAVE) IN OBJECT = V-PUT PRE-PUT>
<SYNTAX DROP OBJECT (HELD MANY HAVE) ON OBJECT = V-PUT-ON PRE-PUT-ON>
<VERB-SYNONYM DROP DUMP>

<SYNTAX EAT OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-EAT>
<VERB-SYNONYM EAT CONSUME SWALLOW DEVOUR GOBBLE NIBBLE ; INGEST>

<SYNTAX GNAW ON OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-EAT>
<SYNTAX GNAW OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-EAT>

<SYNTAX ENTER OBJECT (FIND LOCATION) = V-ENTER>

<SYNTAX EXIT OBJECT (FIND LOCATION) = V-EXIT>
<VERB-SYNONYM EXIT DISMOUNT DEPART SCRAM WITHDRAW>

<SYNTAX EXAMINE OBJECT (HELD CARRIED ON-GROUND IN-ROOM) 
	= V-EXAMINE PRE-EXAMINE>
<SYNTAX EXAMINE IN OBJECT (HELD CARRIED IN-ROOM ON-GROUND)
	= V-LOOK-INSIDE>
<SYNTAX EXAMINE ON OBJECT (HELD CARRIED IN-ROOM ON-GROUND)
	= V-EXAMINE PRE-EXAMINE>
<SYNTAX EXAMINE FOR OBJECT = V-FIND>
<SYNTAX EXAMINE OBJECT (HELD CARRIED ON-GROUND IN-ROOM)
        THROUGH OBJECT (HELD CARRIED ON-GROUND IN-ROOM)
	= V-LOOK-THRU>
<SYNTAX EXAMINE OBJECT (HELD CARRIED ON-GROUND IN-ROOM)
        WITH OBJECT (HELD CARRIED ON-GROUND IN-ROOM)
	= V-LOOK-THRU>
<SYNTAX EXAMINE OBJECT (HELD CARRIED ON-GROUND IN-ROOM)
        IN OBJECT (HELD CARRIED ON-GROUND IN-ROOM)
	= V-EXAMINE-IN PRE-EXAMINE-IN>
<VERB-SYNONYM EXAMINE X INSPECT DESCRIBE CHECK STUDY SURVEY SEE
	      WATCH OBSERVE>

<SYNTAX EXTINGUISH OBJECT = V-LAMP-OFF>
<SYNTAX EXTINGUISH OUT OBJECT = V-LAMP-OFF>
<VERB-SYNONYM EXTINGUISH DOUSE QUENCH SNUFF>

<SYNTAX FILL OBJECT (FIND CONTAINER) (HELD CARRIED) = V-FILL>

<SYNTAX FILL OBJECT (FIND CONTAINER) (HELD CARRIED)
	FROM OBJECT = V-FILL-FROM>
<SYNTAX FILL OBJECT (FIND CONTAINER) (HELD CARRIED)
	WITH OBJECT = V-FILL-FROM>
<SYNTAX FILL OBJECT (FIND CONTAINER) (HELD CARRIED)
	AT OBJECT = V-FILL-FROM>

<SYNTAX SUBMERGE OBJECT (HELD CARRIED HAVE) = V-SUBMERGE>
<SYNTAX SUBMERGE OBJECT (HELD CARRIED HAVE)
	IN OBJECT (ON-GROUND IN-ROOM) = V-PUT-UNDER>
<SYNTAX SUBMERGE OBJECT (HELD CARRIED HAVE)
	UNDER OBJECT (ON-GROUND IN-ROOM) = V-PUT-UNDER>
<VERB-SYNONYM SUBMERGE DIP>

<SYNTAX RUB OBJECT = V-TOUCH>
<SYNTAX RUB OBJECT (HELD CARRIED HAVE) TO OBJECT = V-TOUCH-TO>
<SYNTAX RUB OBJECT (HELD CARRIED HAVE) ON OBJECT = V-TOUCH-TO>
<SYNTAX RUB OBJECT (HELD CARRIED HAVE) OVER OBJECT = V-TOUCH-TO>
<SYNTAX RUB OBJECT (HELD CARRIED HAVE) AGAINST OBJECT = V-TOUCH-TO>
<SYNTAX RUB OBJECT (HELD CARRIED HAVE) IN OBJECT = V-TOUCH-TO>
<SYNTAX RUB TOGETHER OBJECT (HELD CARRIED HAVE) WITH OBJECT = V-TOUCH-TO>
<SYNTAX RUB OBJECT (HELD CARRIED HAVE) TOGETHER OBJECT = V-TOUCH-TO>
<SYNTAX RUB OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-STOUCH-TO>

<SYNTAX RUB OUT OBJECT WITH OBJECT (FIND MANUALLY) (HELD CARRIED HAVE)
	 = V-ERASE-WITH>
<SYNTAX ERASE OBJECT WITH OBJECT (FIND MANUALLY) (HELD CARRIED HAVE)
	= V-ERASE-WITH>

<SYNTAX FIND OBJECT = V-FIND>
<VERB-SYNONYM FIND SEEK DISCOVER>

<SYNTAX HUNT OBJECT = V-FIND>
<SYNTAX HUNT FOR OBJECT = V-FIND>

<SYNTAX DETONATE OBJECT = V-DETONATE>
<VERB-SYNONYM DETONATE EXPLODE>

<SYNTAX SET DOWN OBJECT (HELD CARRIED HAVE) = V-DROP>
<SYNTAX SET ASIDE OBJECT (HELD CARRIED HAVE) = V-UNWIELD>
<SYNTAX SET OFF OBJECT = V-DETONATE>
<SYNTAX SET OBJECT (IN-ROOM ON-GROUND) TO OBJECT = V-POINT-AT PRE-POINT-AT>

<SYNTAX FACE OBJECT (IN-ROOM ON-GROUND) AT OBJECT = V-POINT-AT PRE-POINT-AT>
<SYNTAX FACE OBJECT (IN-ROOM ON-GROUND) TO OBJECT = V-POINT-AT PRE-POINT-AT>
<SYNTAX FACE OBJECT (IN-ROOM ON-GROUND) OBJECT = V-POINT-AT PRE-POINT-AT>

<SYNTAX UNWIELD OBJECT (FIND WIELDED) (HELD CARRIED HAVE) = V-UNWIELD>

<SYNTAX FLY OBJECT (FIND LOCATION) = V-FLY>
<SYNTAX FLY UP OBJECT (FIND LOCATION) = V-FLY-UP>
<SYNTAX FLY DOWN OBJECT (FIND LOCATION) = V-FLY-DOWN>
<SYNTAX FLY ON OBJECT = V-FLY>
<SYNTAX FLY WITH OBJECT = V-FLY>
<SYNTAX FLY OVER OBJECT = V-FLY>

<SYNTAX BANK OBJECT (FIND LOCATION) = V-BANK>
<SYNTAX BANK TO OBJECT = V-BANK>

<SYNTAX LAND = V-LAND>
<SYNTAX LAND ON OBJECT = V-LAND-ON>

<SYNTAX REFUSE OBJECT = V-REFUSE>

<SYNTAX FOLD OBJECT (HELD CARRIED HAVE) = V-FOLD>
<SYNTAX FOLD UP OBJECT (HELD CARRIED HAVE) = V-FOLD>
<SYNTAX FOLD OBJECT (HELD CARRIED HAVE) AROUND OBJECT (ON-GROUND IN-ROOM)
	= V-WRAP-AROUND>
<SYNTAX FOLD OBJECT IN OBJECT = V-SWRAP>
<SYNTAX FOLD UP OBJECT (ON-GROUND IN-ROOM) IN OBJECT (HELD CARRIED HAVE)
	= V-SWRAP>
<VERB-SYNONYM FOLD WRAP>

<SYNTAX FOLLOW OBJECT = V-FOLLOW>
<VERB-SYNONYM FOLLOW PURSUE CHASE>

; <SYNTAX HANG UP OBJECT (FIND LOCATION) = V-HANGUP>

<SYNTAX HANG OBJECT = V-HANG>
<SYNTAX HANG OBJECT (HELD CARRIED HAVE) ON OBJECT = V-HANG-ON>
<SYNTAX HANG OBJECT (HELD CARRIED HAVE) FROM OBJECT = V-HANG-ON>
<SYNTAX HANG UP OBJECT (HELD CARRIED HAVE) ON OBJECT = V-HANG-ON>
<VERB-SYNONYM HANG HOOK>

<SYNTAX SUSPEND OBJECT = V-HANG>
<SYNTAX SUSPEND OBJECT (HELD CARRIED HAVE) ON OBJECT = V-HANG-ON>
<SYNTAX SUSPEND OBJECT (HELD CARRIED HAVE) FROM OBJECT = V-HANG-ON>

<SYNTAX HAND OBJECT (HELD CARRIED HAVE ; TAKE)
	TO OBJECT (FIND LIVING) (IN-ROOM ON-GROUND) = V-GIVE PRE-GIVE>
<SYNTAX HAND OBJECT (FIND LIVING) (ON-GROUND IN-ROOM)
	OBJECT (HELD CARRIED HAVE ; TAKE) = V-SGIVE>
<VERB-SYNONYM HAND GIVE DONATE DELIVER BESTOW PRESENT>

<SYNTAX SHOW OBJECT (HELD CARRIED HAVE ; TAKE) TO OBJECT
        (FIND LIVING) (IN-ROOM ON-GROUND) = V-SHOW PRE-SHOW>
<SYNTAX SHOW OBJECT (FIND LIVING) OBJECT
	(HELD CARRIED HAVE ; TAKE) = V-SSHOW>
<VERB-SYNONYM SHOW DISPLAY>

<SYNTAX FEED OBJECT (FIND LIVING) (ON-GROUND IN-ROOM) 
	WITH OBJECT (HELD CARRIED HAVE) = V-SFEED>
<SYNTAX FEED OBJECT (HELD CARRIED HAVE) 
	TO OBJECT (FIND LIVING) (ON-GROUND IN-ROOM) = V-FEED PRE-FEED>
<SYNTAX FEED OBJECT (FIND LIVING) (ON-GROUND IN-ROOM)
        OBJECT (HELD CARRIED HAVE) = V-SFEED>

<SYNTAX HEAR OBJECT = V-LISTEN>

<SYNTAX HELLO OBJECT (FIND LOCATION) = V-HELLO>
<VERB-SYNONYM HELLO HI GREETINGS GREET SALUTE>

<SYNTAX BYE OBJECT (FIND LOCATION) = V-GOODBYE>
<VERB-SYNONYM BYE GOODBYE FAREWELL>

<SYNTAX HINT = V-HELP>
<VERB-SYNONYM HINT HINTS>

<SYNTAX HELP = V-HELP>
<SYNTAX HELP OBJECT = V-RESCUE>
<VERB-SYNONYM HELP AID>

<SYNTAX CONCEAL OBJECT (HELD CARRIED HAVE) IN OBJECT
	(ON-GROUND IN-ROOM) = V-PUT PRE-PUT>
<SYNTAX CONCEAL OBJECT (HELD CARRIED HAVE) BEHIND OBJECT (ON-GROUND IN-ROOM)
	= V-PUT-BEHIND>
<SYNTAX CONCEAL OBJECT (HELD CARRIED HAVE) UNDER OBJECT (ON-GROUND IN-ROOM)
	= V-PUT-UNDER>

<SYNTAX HIDE OBJECT (FIND LOCATION) = V-HIDE>

<SYNTAX HIDE UNDER OBJECT = V-STAND-UNDER>
<SYNTAX HIDE IN OBJECT = V-ENTER>
<SYNTAX HIDE BEHIND OBJECT = V-WALK-AROUND>
<SYNTAX HIDE OBJECT (HELD CARRIED HAVE) BEHIND OBJECT (ON-GROUND IN-ROOM)
	= V-PUT-BEHIND>
<SYNTAX HIDE OBJECT (HELD CARRIED HAVE) UNDER OBJECT (ON-GROUND IN-ROOM)
	= V-PUT-UNDER>

<SYNTAX COVER OBJECT (ON-GROUND IN-ROOM)
	WITH OBJECT (HELD CARRIED HAVE) = V-COVER>
<SYNTAX COVER UP OBJECT (ON-GROUND IN-ROOM)
	WITH OBJECT (HELD CARRIED HAVE) = V-COVER>
<SYNTAX COVER OVER OBJECT (ON-GROUND IN-ROOM)
	WITH OBJECT (HELD CARRIED HAVE) = V-COVER>
<VERB-SYNONYM COVER BLOCK SHIELD>

<SYNTAX INFLATE OBJECT = V-BLOW-INTO>
<SYNTAX DEFLATE OBJECT = V-DEFLATE>

<SYNTAX JUMP OBJECT (FIND LOCATION) = V-LEAP>
<SYNTAX JUMP UP OBJECT (FIND LOCATION) = V-CLIMB-UP>
<SYNTAX JUMP DOWN OBJECT (FIND LOCATION) = V-CLIMB-DOWN>
<SYNTAX JUMP ON OBJECT = V-STAND-ON>
<SYNTAX JUMP OVER OBJECT = V-CLIMB-OVER>
<SYNTAX JUMP IN OBJECT (FIND LOCATION) = V-LEAP>
<SYNTAX JUMP TO OBJECT = V-ENTER>
<SYNTAX JUMP THROUGH OBJECT = V-ENTER>
<SYNTAX JUMP OUT OBJECT (FIND LOCATION) = V-EXIT>
<SYNTAX JUMP FROM OBJECT = V-CLIMB-DOWN>
<SYNTAX JUMP OFF OBJECT (FIND LOCATION) = V-CLIMB-DOWN>
<VERB-SYNONYM JUMP LEAP BOUND HURDLE VAULT>

<SYNTAX BOUNCE OBJECT (FIND LOCATION) (HELD CARRIED HAVE) = V-BOUNCE>
<SYNTAX BOUNCE AROUND OBJECT (FIND LOCATION) (HELD CARRIED HAVE) = V-BOUNCE>
<VERB-SYNONYM BOUNCE ; DRIBBLE>

<SYNTAX KICK OBJECT = V-KICK>
<SYNTAX KICK AROUND OBJECT = V-KICK>

<SYNTAX KICK IN OBJECT = V-MUNG>
<SYNTAX KICK DOWN OBJECT = V-MUNG>

<SYNTAX STAMP ON OBJECT = V-MUNG>
<SYNTAX STAMP DOWN OBJECT = V-MUNG>
<SYNTAX STAMP OVER OBJECT = V-MUNG>
<VERB-SYNONYM STAMP TRAMPLE>


<SYNTAX ATTACK OBJECT (ON-GROUND IN-ROOM)
	WITH OBJECT (FIND WIELDED) (HELD CARRIED HAVE) = V-HIT PRE-HIT>
<VERB-SYNONYM ATTACK ASSAULT FIGHT HURT INJURE KILL MURDER SLAY
	      STAB WOUND VANQUISH>

<SYNTAX HIT OBJECT (ON-GROUND IN-ROOM)
        WITH OBJECT (FIND WIELDED) (HELD CARRIED HAVE) = V-HIT PRE-HIT>
<SYNTAX HIT AT OBJECT (ON-GROUND IN-ROOM)
	WITH OBJECT (FIND WIELDED) (HELD CARRIED HAVE) = V-HIT PRE-HIT>
<SYNTAX HIT OBJECT (HELD CARRIED HAVE)
	ON OBJECT (ON-GROUND IN-ROOM) = V-SHIT>
<VERB-SYNONYM HIT BATTLE COMBAT STRIKE WHACK SWAT POKE JAB BLIND>

<SYNTAX PUNCH OBJECT = V-PUNCH>
<SYNTAX PUNCH OBJECT (ON-GROUND IN-ROOM)
        WITH OBJECT (FIND WIELDED) (HELD CARRIED HAVE) = V-HIT PRE-HIT>
<SYNTAX PUNCH AT OBJECT (ON-GROUND IN-ROOM)
	WITH OBJECT (FIND WIELDED) (HELD CARRIED HAVE) = V-HIT PRE-HIT>
<VERB-SYNONYM PUNCH SLAP>

<SYNTAX PARRY = V-PARRY>
<SYNTAX PARRY OBJECT (ON-GROUND IN-ROOM) = V-PARRY>
<SYNTAX PARRY AGAINST OBJECT (ON-GROUND IN-ROOM) = V-PARRY>
<SYNTAX PARRY WITH OBJECT (ON-GROUND IN-ROOM) = V-PARRY>
<VERB-SYNONYM PARRY DEFEND FEINT>

<SYNTAX THRUST = V-THRUST>
<SYNTAX THRUST AT OBJECT (ON-GROUND IN-ROOM)
	WITH OBJECT (FIND WIELDED) (HELD CARRIED HAVE) = V-HIT PRE-HIT>
<SYNTAX THRUST OBJECT (HELD CARRIED HAVE) 
	AT OBJECT (ON-GROUND IN-ROOM) = V-SHIT>

<SYNTAX LUNGE = V-THRUST>
<SYNTAX LUNGE AT OBJECT (ON-GROUND IN-ROOM)
	WITH OBJECT (FIND WIELDED) (HELD CARRIED HAVE) = V-HIT PRE-HIT>

<SYNTAX THRUST UP OBJECT (IN-ROOM ON-GROUND) = V-RAISE>
<SYNTAX THRUST DOWN OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-LOOSEN>
<SYNTAX THRUST OBJECT (IN-ROOM ON-GROUND) OBJECT = V-PUSH-TO>
<SYNTAX THRUST OBJECT (IN-ROOM ON-GROUND) TO OBJECT = V-PUSH-TO>
<SYNTAX THRUST OBJECT (IN-ROOM ON-GROUND) IN OBJECT = V-PUSH-TO>
<SYNTAX THRUST OBJECT (IN-ROOM ON-GROUND) ON OBJECT = V-PUSH-TO>
<SYNTAX THRUST OBJECT (IN-ROOM ON-GROUND) UP OBJECT = V-PUSH-UP>
<SYNTAX THRUST OBJECT (IN-ROOM ON-GROUND) DOWN OBJECT = V-PUSH-DOWN>
<SYNTAX THRUST OBJECT (IN-ROOM ON-GROUND) OVER OBJECT = V-PUSH-TO>
<SYNTAX THRUST OBJECT (ON-GROUND IN-ROOM) UNDER OBJECT = V-PUT-UNDER>

<SYNTAX KNOCK AT OBJECT = V-KNOCK>
<SYNTAX KNOCK ON OBJECT = V-KNOCK>
<SYNTAX KNOCK DOWN OBJECT (FIND MONSTER) (ON-GROUND IN-ROOM) = V-HIT PRE-HIT>
<SYNTAX KNOCK OUT OBJECT (FIND MONSTER) (ON-GROUND IN-ROOM) = V-HIT PRE-HIT>
<SYNTAX KNOCK OBJECT (FIND MONSTER) (ON-GROUND IN-ROOM) = V-HIT PRE-HIT>
<SYNTAX KNOCK DOWN OBJECT (FIND MONSTER) (ON-GROUND IN-ROOM)
	WITH OBJECT (HELD CARRIED HAVE) = V-HIT PRE-HIT>
<SYNTAX KNOCK OUT OBJECT (FIND MONSTER) (ON-GROUND IN-ROOM)
	WITH OBJECT (HELD CARRIED HAVE) = V-HIT PRE-HIT>
<SYNTAX KNOCK OBJECT (FIND MONSTER) (ON-GROUND IN-ROOM)
	WITH OBJECT (HELD CARRIED HAVE) = V-HIT PRE-HIT>
<VERB-SYNONYM KNOCK RAP POUND>

<SYNTAX PEEL OBJECT = V-PEEL>
<SYNTAX PEEL OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-CUT>

<SYNTAX KISS OBJECT (FIND PERSON) (ON-GROUND IN-ROOM) = V-KISS>
<VERB-SYNONYM KISS SMOOCH>

<SYNTAX LEAVE OBJECT (FIND LOCATION) = V-LEAVE>
<SYNTAX LEAVE OBJECT (HELD CARRIED ; HAVE MANY) IN OBJECT
	(ON-GROUND IN-ROOM CARRIED ; MANY) = V-PUT PRE-PUT>
<SYNTAX LEAVE OBJECT (HELD CARRIED ; HAVE MANY) ON OBJECT
	(ON-GROUND IN-ROOM CARRIED ; MANY) = V-PUT-ON PRE-PUT-ON>

<SYNTAX LIE DOWN OBJECT (FIND LOCATION) = V-LIE-DOWN>
<SYNTAX LIE ON OBJECT = V-LIE-DOWN>
<SYNTAX LIE IN OBJECT = V-LIE-DOWN>
<VERB-SYNONYM LIE RECLINE>

<SYNTAX LISTEN OBJECT (FIND LOCATION) = V-LISTEN>
<SYNTAX LISTEN TO OBJECT (HELD CARRIED ON-GROUND IN-ROOM) 
	= V-LISTEN>
<SYNTAX LISTEN IN OBJECT (HELD CARRIED ON-GROUND IN-ROOM)
        = V-LISTEN>
<SYNTAX LISTEN FOR OBJECT (HELD CARRIED ON-GROUND IN-ROOM)
	= V-LISTEN>

<SYNTAX LOCK OBJECT (ON-GROUND IN-ROOM) 
	WITH OBJECT (FIND MANUALLY) (HELD HAVE) = V-LOCK>

<SYNTAX LOOK = V-LOOK>
<SYNTAX LOOK AT OBJECT (HELD CARRIED ON-GROUND IN-ROOM)
	= V-EXAMINE PRE-EXAMINE>
<SYNTAX LOOK AROUND OBJECT (FIND LOCATION) = V-LOOK>
<SYNTAX LOOK DOWN OBJECT (FIND LOCATION) = V-LOOK-DOWN>
<SYNTAX LOOK OVER OBJECT (HELD CARRIED ON-GROUND IN-ROOM)
	= V-EXAMINE PRE-EXAMINE>
<SYNTAX LOOK UP OBJECT (FIND LOCATION) = V-LOOK-UP>
<SYNTAX LOOK OBJECT (HELD CARRIED ON-GROUND IN-ROOM) 
	= V-DUMB-EXAMINE PRE-DUMB-EXAMINE>
<SYNTAX LOOK THROUGH OBJECT (HELD CARRIED ON-GROUND IN-ROOM)
	= V-LOOK-INSIDE>
<SYNTAX LOOK THROUGH OBJECT AT OBJECT = V-SLOOK-THRU>
<SYNTAX LOOK UNDER OBJECT = V-LOOK-UNDER>
<SYNTAX LOOK BEHIND OBJECT = V-LOOK-BEHIND>
<SYNTAX LOOK IN OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-LOOK-INSIDE>
<SYNTAX LOOK ON OBJECT (HELD CARRIED ON-GROUND IN-ROOM) 
	= V-LOOK-ON>
<SYNTAX LOOK AT OBJECT (HELD CARRIED ON-GROUND IN-ROOM) THROUGH OBJECT
	= V-LOOK-THRU>
<SYNTAX LOOK AT OBJECT (HELD CARRIED ON-GROUND IN-ROOM) WITH OBJECT
	= V-LOOK-THRU>
<SYNTAX LOOK AT OBJECT (HELD CARRIED ON-GROUND IN-ROOM)
	IN OBJECT = V-EXAMINE-IN PRE-EXAMINE-IN>
<SYNTAX LOOK IN OBJECT (HELD CARRIED ON-GROUND IN-ROOM) THROUGH OBJECT
	= V-LOOK-THRU>
<SYNTAX LOOK IN OBJECT (HELD CARRIED ON-GROUND IN-ROOM) WITH OBJECT
	= V-LOOK-THRU>
<SYNTAX LOOK OUT OBJECT (FIND LOCATION) = V-LOOK-OUTSIDE>
<SYNTAX LOOK FOR OBJECT = V-FIND>
<SYNTAX LOOK TO OBJECT (HELD CARRIED ON-GROUND IN-ROOM) 
	= V-EXAMINE PRE-EXAMINE>
<VERB-SYNONYM LOOK L STARE GAZE PEER PEEK>

<SYNTAX ADJUST OBJECT (HELD CARRIED) = V-ADJUST>

<SYNTAX LOOSEN OBJECT WITH OBJECT (FIND MANUALLY) (HELD CARRIED HAVE ; TAKE)
	= V-LOOSEN>
<VERB-SYNONYM LOOSEN JIGGLE WIGGLE WOBBLE>

<SYNTAX PRY OBJECT WITH OBJECT (FIND MANUALLY) (HELD CARRIED HAVE ; TAKE)
	= V-LOOSEN>
<SYNTAX PRY UP OBJECT WITH OBJECT (FIND MANUALLY) (HELD CARRIED HAVE ; TAKE) 
	= V-LOOSEN>
<SYNTAX PRY OUT OBJECT WITH OBJECT (FIND MANUALLY) (HELD CARRIED HAVE ; TAKE)
	= V-LOOSEN>

<SYNTAX LOWER OBJECT = V-LOWER>

<SYNTAX MAKE OBJECT = V-MAKE>
<SYNTAX MAKE UP OBJECT = V-MAKE>

<SYNTAX MOVE OBJECT (FIND LOCATION) (ON-GROUND IN-ROOM) = V-MOVE>
<SYNTAX MOVE OVER OBJECT (FIND LOCATION) (ON-GROUND IN-ROOM) = V-MOVE>
<SYNTAX MOVE UP OBJECT (ON-GROUND IN-ROOM) = V-RAISE>
<SYNTAX MOVE DOWN OBJECT (ON-GROUND IN-ROOM) = V-LOWER>
<SYNTAX MOVE OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-LOOSEN>
<SYNTAX MOVE OBJECT (ON-GROUND IN-ROOM) OBJECT = V-PUSH-TO>
<SYNTAX MOVE OBJECT (ON-GROUND IN-ROOM) TO OBJECT = V-PUSH-TO>
<SYNTAX MOVE OBJECT (ON-GROUND IN-ROOM) IN OBJECT = V-PUSH-TO>
<SYNTAX MOVE OBJECT (ON-GROUND IN-ROOM) UP OBJECT = V-PUSH-UP>
<SYNTAX MOVE OBJECT (ON-GROUND IN-ROOM) ON OBJECT = V-PUSH-UP>
<SYNTAX MOVE OBJECT (ON-GROUND IN-ROOM) DOWN OBJECT = V-PUSH-DOWN>
<SYNTAX MOVE OVER OBJECT (ON-GROUND IN-ROOM) TO OBJECT = V-PUSH-TO>
<VERB-SYNONYM MOVE SHIFT DISLOCATE ROLL>

<SYNTAX LEAN ON OBJECT = V-PUSH>
<SYNTAX LEAN OBJECT (HELD CARRIED HAVE) ON OBJECT = V-PUT-ON PRE-PUT-ON>
<SYNTAX LEAN OBJECT (HELD CARRIED HAVE)	UP OBJECT = V-PUT-ON PRE-PUT-ON>
<SYNTAX LEAN OBJECT (HELD CARRIED HAVE) AGAINST OBJECT = V-PUT-ON PRE-PUT-ON>

<SYNTAX PROP UP OBJECT = V-PULL>
<SYNTAX PROP UP (HELD CARRIED HAVE) OBJECT ON OBJECT = V-PUT-ON PRE-PUT-ON>
<SYNTAX PROP OBJECT (HELD CARRIED HAVE) AGAINST OBJECT = V-PUT-ON PRE-PUT-ON>
<SYNTAX PROP UP OBJECT (HELD CARRIED HAVE) AGAINST OBJECT 
	= V-PUT-ON PRE-PUT-ON>

<SYNTAX OPEN OBJECT (FIND OPENABLE) (HELD CARRIED ON-GROUND IN-ROOM)
	= V-OPEN>
<SYNTAX OPEN UP	OBJECT (FIND OPENABLE) (HELD CARRIED ON-GROUND IN-ROOM)
	= V-OPEN>
<SYNTAX OPEN OBJECT (FIND OPENABLE) (HELD CARRIED ON-GROUND IN-ROOM)
	WITH OBJECT (HELD CARRIED HAVE)
	= V-OPEN-WITH>
<SYNTAX OPEN UP OBJECT (FIND OPENABLE) (HELD CARRIED ON-GROUND IN-ROOM)
	WITH OBJECT (HELD CARRIED HAVE)
	= V-OPEN-WITH>
<VERB-SYNONYM OPEN UNSEAL DISASSEMBLE>

<SYNTAX PRAY = V-HELP>

<SYNTAX PULL OBJECT (ON-GROUND IN-ROOM) = V-PULL>
<SYNTAX PULL ON OBJECT (ON-GROUND IN-ROOM) = V-PULL>
<SYNTAX PULL ON OBJECT (ON-GROUND IN-ROOM) WITH OBJECT
        (HELD CARRIED HAVE) = V-LOOSEN>
<SYNTAX PULL UP OBJECT (ON-GROUND IN-ROOM) = V-RAISE>
<SYNTAX PULL UP OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (HELD CARRIED HAVE)
        = V-LOOSEN>
<SYNTAX PULL DOWN OBJECT (ON-GROUND IN-ROOM) = V-LOWER>
<SYNTAX PULL DOWN OBJECT (ON-GROUND IN-ROOM) WITH OBJECT
        (HELD CARRIED HAVE) = V-LOOSEN>
<SYNTAX PULL OBJECT (ON-GROUND IN-ROOM) WITH OBJECT
        (HELD CARRIED HAVE) = V-LOOSEN>
<SYNTAX PULL OBJECT (FIND TAKEABLE) OUT OBJECT (ON-GROUND IN-ROOM)
	= V-TAKE PRE-TAKE>
<SYNTAX PULL OBJECT (FIND TAKEABLE) OFF OBJECT (ON-GROUND IN-ROOM)
	= V-TAKE PRE-TAKE>
<SYNTAX PULL OBJECT (ON-GROUND IN-ROOM) OBJECT = V-PUSH-TO>
<SYNTAX PULL OBJECT (ON-GROUND IN-ROOM) TO OBJECT = V-PUSH-TO>
<SYNTAX PULL APART OBJECT (ON-GROUND IN-ROOM) = V-OPEN>
<SYNTAX PULL OUT OBJECT = V-UNPLUG>
<VERB-SYNONYM PULL TUG DRAG YANK>

<SYNTAX PICK OBJECT WITH OBJECT (FIND MANUALLY) (HELD CARRIED HAVE) = V-PICK>
<SYNTAX PICK UP OBJECT (FIND TAKEABLE) (ON-GROUND MANY) = V-TAKE PRE-TAKE>

<SYNTAX PLAY OBJECT (FIND LOCATION) = V-TOUCH>
<SYNTAX PLAY WITH OBJECT = V-TOUCH>
<VERB-SYNONYM PLAY FIDDLE TOY CAVORT>

<SYNTAX POINT OBJECT = V-POINT>
<SYNTAX POINT AT OBJECT = V-POINT>
<SYNTAX POINT AT OBJECT FOR OBJECT (FIND LIVING) = V-POINT>
<SYNTAX POINT TO OBJECT = V-POINT>
<SYNTAX POINT TO OBJECT FOR OBJECT (FIND LIVING) = V-POINT>
<SYNTAX POINT OUT OBJECT TO OBJECT (FIND LIVING) = V-POINT>
<SYNTAX POINT AT OBJECT WITH OBJECT = V-SPOINT-AT>
<SYNTAX POINT OBJECT (IN-ROOM ON-GROUND) AT OBJECT = V-POINT-AT PRE-POINT-AT>
<SYNTAX POINT OBJECT (IN-ROOM ON-GROUND) TO OBJECT = V-POINT-AT PRE-POINT-AT>
<SYNTAX POINT OBJECT (IN-ROOM ON-GROUND) OBJECT = V-POINT-AT PRE-POINT-AT>

<SYNTAX SELECT OBJECT = V-POINT>
<VERB-SYNONYM SELECT CHOOSE>

" <SYNTAX SHINE OBJECT (FIND LIGHTED) (HELD CARRIED HAVE)
	AT OBJECT (ON-GROUND IN-ROOM) = V-SHINE-AT>
  <SYNTAX SHINE OBJECT (FIND LIGHTED) (HELD CARRIED HAVE)
	IN OBJECT (ON-GROUND IN-ROOM) = V-SHINE-AT>
  <SYNTAX SHINE OBJECT (FIND LIGHTED) (HELD CARRIED HAVE)
	ON OBJECT (ON-GROUND IN-ROOM) = V-SHINE-AT>
  <SYNTAX SHINE OBJECT (FIND LIGHTED) (HELD CARRIED HAVE)
	OVER OBJECT (ON-GROUND IN-ROOM) = V-SHINE-AT>
  <SYNTAX SHINE ON OBJECT (ON-GROUND IN-ROOM)
	WITH OBJECT (FIND LIGHTED) (HELD CARRIED HAVE) = V-SSHINE-AT>
  <SYNTAX SHINE IN OBJECT (ON-GROUND IN-ROOM)
	WITH OBJECT (FIND LIGHTED) (HELD CARRIED HAVE) = V-SSHINE-AT>
  <SYNTAX SHINE OVER OBJECT (ON-GROUND IN-ROOM)
	WITH OBJECT (FIND LIGHTED) (HELD CARRIED HAVE) = V-SSHINE-AT>

  <SYNTAX FLASH OBJECT (FIND LIGHTED) (HELD CARRIED HAVE)
	AT OBJECT (ON-GROUND IN-ROOM) = V-SHINE-AT>
  <SYNTAX FLASH OBJECT (FIND LIGHTED) (HELD CARRIED HAVE)
	IN OBJECT (ON-GROUND IN-ROOM) = V-SHINE-AT>
  <SYNTAX FLASH OBJECT (FIND LIGHTED) (HELD CARRIED HAVE)
	ON OBJECT (ON-GROUND IN-ROOM) = V-SHINE-AT>
  <SYNTAX FLASH OBJECT (FIND LIGHTED) (HELD CARRIED HAVE)
	OVER OBJECT (ON-GROUND IN-ROOM) = V-SHINE-AT>

  <SYNTAX ILLUMINATE OBJECT (ON-GROUND IN-ROOM)
	WITH OBJECT (FIND LIGHTED) (HELD CARRIED HAVE) = V-SSHINE-AT> "

<SYNTAX LIGHT OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-LIGHT-WITH>
<SYNTAX LIGHT UP OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-LIGHT-WITH>
<SYNTAX LIGHT OBJECT (ON-GROUND IN-ROOM)
	WITH OBJECT (FIND MANUALLY) (HELD CARRIED HAVE) = V-LIGHT-WITH>
<SYNTAX LIGHT UP OBJECT (ON-GROUND IN-ROOM)
	WITH OBJECT (FIND MANUALLY) (HELD CARRIED HAVE) = V-LIGHT-WITH>
<SYNTAX LIGHT OBJECT (HELD CARRIED HAVE) 
	ON OBJECT (ON-GROUND IN-ROOM) = V-LIGHT-ON>

<SYNTAX AIM AT OBJECT WITH OBJECT = V-SPOINT-AT>
<SYNTAX AIM OBJECT AT OBJECT = V-POINT-AT PRE-POINT-AT>
<SYNTAX AIM OBJECT TO OBJECT = V-POINT-AT PRE-POINT-AT>

<SYNTAX POP OBJECT WITH OBJECT (FIND MANUALLY) (HELD CARRIED HAVE) = V-POP>
<VERB-SYNONYM POP BURST>

<SYNTAX POUR OBJECT (HELD CARRIED HAVE) = V-POUR>
<SYNTAX POUR OUT OBJECT (HELD CARRIED HAVE) = V-POUR>

<SYNTAX POUR OBJECT (HELD CARRIED HAVE) IN OBJECT = V-EMPTY-INTO>
<SYNTAX POUR OUT OBJECT (HELD CARRIED HAVE) IN OBJECT = V-EMPTY-INTO>
<SYNTAX POUR OBJECT (HELD CARRIED HAVE) ON OBJECT = V-EMPTY-INTO>
<SYNTAX POUR OUT OBJECT (HELD CARRIED HAVE) ON OBJECT = V-EMPTY-INTO>

<SYNTAX POUR OBJECT FROM OBJECT (HELD CARRIED HAVE) = V-POUR-FROM>
<SYNTAX POUR OUT OBJECT FROM OBJECT (HELD CARRIED HAVE) = V-POUR-FROM>
<SYNTAX POUR OBJECT OUT OBJECT (HELD CARRIED HAVE) = V-POUR-FROM>

<VERB-SYNONYM POUR SPILL SPRINKLE>

<SYNTAX EMPTY OBJECT (HELD CARRIED) = V-EMPTY>
<SYNTAX EMPTY OUT OBJECT (HELD CARRIED) = V-EMPTY>
<SYNTAX EMPTY OFF OBJECT (HELD CARRIED) = V-EMPTY>

<SYNTAX EMPTY OBJECT FROM OBJECT = V-TAKE PRE-TAKE>
<SYNTAX EMPTY OUT OBJECT FROM OBJECT = V-TAKE PRE-TAKE>
<SYNTAX EMPTY OBJECT OUT OBJECT = V-TAKE PRE-TAKE>

<SYNTAX EMPTY OBJECT (HELD CARRIED HAVE) IN OBJECT = V-EMPTY-INTO>
<SYNTAX EMPTY OBJECT (HELD CARRIED HAVE) ON OBJECT = V-EMPTY-INTO>
<SYNTAX EMPTY OUT OBJECT (HELD CARRIED HAVE) IN OBJECT = V-EMPTY-INTO>
<SYNTAX EMPTY OUT OBJECT (HELD CARRIED HAVE) ON OBJECT = V-EMPTY-INTO>

<VERB-SYNONYM EMPTY CLEAR>

<SYNTAX PUSH OBJECT (IN-ROOM ON-GROUND) = V-PUSH>
<SYNTAX PUSH ON OBJECT (IN-ROOM ON-GROUND) = V-PUSH>
<SYNTAX PUSH UP OBJECT (IN-ROOM ON-GROUND) = V-RAISE>
<SYNTAX PUSH DOWN OBJECT (IN-ROOM ON-GROUND) = V-LOWER>
<SYNTAX PUSH IN OBJECT TO OBJECT = V-PLUG-IN>
<SYNTAX PUSH OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-LOOSEN>
<SYNTAX PUSH DOWN OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-LOOSEN>
<SYNTAX PUSH ON OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-LOOSEN>
<SYNTAX PUSH OBJECT (IN-ROOM ON-GROUND) OBJECT = V-PUSH-TO>
<SYNTAX PUSH OBJECT (IN-ROOM ON-GROUND) TO OBJECT = V-PUSH-TO>
<SYNTAX PUSH OBJECT (IN-ROOM ON-GROUND) IN OBJECT = V-PUSH-TO>
<SYNTAX PUSH OBJECT (IN-ROOM ON-GROUND) ON OBJECT = V-PUSH-TO>
<SYNTAX PUSH OBJECT (IN-ROOM ON-GROUND) UP OBJECT = V-PUSH-UP>
<SYNTAX PUSH OBJECT (IN-ROOM ON-GROUND) DOWN OBJECT = V-PUSH-DOWN>
<SYNTAX PUSH OBJECT (IN-ROOM ON-GROUND) OVER OBJECT = V-PUSH-TO>
<SYNTAX PUSH OBJECT (ON-GROUND IN-ROOM) UNDER OBJECT = V-PUT-UNDER>
<SYNTAX PUSH OBJECT (ON-GROUND IN-ROOM) AT OBJECT = V-PUSH-TO>
<VERB-SYNONYM PUSH PRESS SHOVE NUDGE STICK>

<SYNTAX PUT OBJECT (HELD CARRIED HAVE MANY) IN OBJECT
	(ON-GROUND IN-ROOM CARRIED) = V-PUT PRE-PUT>
<SYNTAX PUT OBJECT (HELD CARRIED HAVE MANY) DOWN OBJECT
	(ON-GROUND IN-ROOM CARRIED) = V-PUT PRE-PUT>
<SYNTAX PUT OBJECT (HELD CARRIED HAVE MANY) ON OBJECT
	(ON-GROUND IN-ROOM CARRIED) = V-PUT-ON PRE-PUT-ON>
<SYNTAX PUT OBJECT (HELD CARRIED HAVE) AGAINST OBJECT
	(ON-GROUND IN-ROOM CARRIED) = V-TOUCH-TO>
<SYNTAX PUT OBJECT (HELD CARRIED HAVE) THROUGH OBJECT
	(ON-GROUND IN-ROOM CARRIED) = V-THROW PRE-THROW>
<SYNTAX PUT OBJECT (HELD CARRIED HAVE) OVER OBJECT
	(ON-GROUND IN-ROOM CARRIED) = V-PUT-ON PRE-PUT-ON>
<SYNTAX PUT DOWN OBJECT (HELD CARRIED HAVE MANY) = V-DROP>
<SYNTAX PUT OBJECT (HELD HAVE CARRIED MANY) UNDER OBJECT
	(ON-GROUND IN-ROOM CARRIED) = V-PUT-UNDER> 
<SYNTAX PUT ON OBJECT (ON-GROUND IN-ROOM CARRIED) = V-WEAR>
<SYNTAX PUT OBJECT (HELD CARRIED MANY HAVE) BEHIND OBJECT
	(ON-GROUND IN-ROOM CARRIED) = V-PUT-BEHIND>
<SYNTAX PUT OUT OBJECT (ON-GROUND IN-ROOM CARRIED HELD) = V-LAMP-OFF>
<SYNTAX PUT ASIDE OBJECT (HELD CARRIED HAVE) = V-UNWIELD>
<VERB-SYNONYM PUT STUFF INSERT PLACE LAY STASH>

<SYNTAX WEDGE OBJECT (HELD CARRIED HAVE) IN OBJECT = V-WEDGE>
<SYNTAX WEDGE OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-LOOSEN>
<SYNTAX WEDGE UP OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-LOOSEN>
<VERB-SYNONYM WEDGE FORCE>

<SYNTAX PLUG IN OBJECT TO OBJECT = V-PLUG-IN>
<SYNTAX PLUG OBJECT IN OBJECT = V-PLUG-IN>
<SYNTAX PLUG OBJECT ON OBJECT = V-PLUG-IN>
<VERB-SYNONYM PLUG SCREW TIGHTEN>

<SYNTAX CONNECT OBJECT TO OBJECT (ON-GROUND IN-ROOM) = V-PLUG-IN>
<SYNTAX CONNECT OBJECT IN OBJECT (ON-GROUND IN-ROOM) = V-PLUG-IN>
<VERB-SYNONYM CONNECT ATTACH JOIN>

<SYNTAX UNPLUG OBJECT = V-UNPLUG>
<SYNTAX UNPLUG OBJECT FROM OBJECT (ON-GROUND IN-ROOM) = V-UNPLUG>
<VERB-SYNONYM UNPLUG UNSCREW DISCONNEC DETACH UNATTACH DISENGAGE>

<SYNTAX RAISE OBJECT = V-RAISE>
<SYNTAX RAISE UP OBJECT = V-RAISE>
<SYNTAX RAISE OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-LOOSEN>
<SYNTAX RAISE UP OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-LOOSEN>
<VERB-SYNONYM RAISE LIFT ELEVATE HOIST>

<SYNTAX RAPE OBJECT (FIND LIVING) = V-RAPE>
<VERB-SYNONYM RAPE MOLEST DEFILE RAVISH HUMP>

<SYNTAX REACH OBJECT WITH OBJECT (FIND TOOL) = V-STOUCH-TO>
<SYNTAX REACH FOR OBJECT WITH OBJECT (FIND TOOL) = V-STOUCH-TO>
<SYNTAX REACH OUT OBJECT WITH OBJECT (FIND TOOL) = V-STOUCH-TO>
<SYNTAX REACH TO OBJECT WITH OBJECT (FIND TOOL) = V-STOUCH-TO>
<SYNTAX REACH IN OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-REACH-IN>
<SYNTAX REACH THROUGH OBJECT (ON-GROUND IN-ROOM) = V-REACH-IN>
<VERB-SYNONYM REACH GROPE>

<SYNTAX READ OBJECT (FIND READABLE) (HELD CARRIED ON-GROUND IN-ROOM)
	= V-READ>
<SYNTAX READ THROUGH OBJECT (FIND READABLE) (HELD CARRIED ON-GROUND IN-ROOM)
	= V-READ>
<SYNTAX READ OBJECT (FIND READABLE) (HELD CARRIED ON-GROUND IN-ROOM)
	THROUGH OBJECT = V-LOOK-THRU>
<SYNTAX READ OBJECT (FIND READABLE) (HELD CARRIED ON-GROUND IN-ROOM)
	TO OBJECT (FIND PERSON) = V-READ-TO>
<VERB-SYNONYM READ SKIM BROWSE LEAF>

<SYNTAX RELEASE OBJECT  (ON-GROUND IN-ROOM HELD CARRIED)
	WITH OBJECT (FIND MANUALLY) (HAVE) = V-RELEASE>
<SYNTAX RELEASE OBJECT  (ON-GROUND IN-ROOM HELD CARRIED)
	FROM OBJECT (FIND MANUALLY) = V-RELEASE>
<VERB-SYNONYM RELEASE FREE>

<SYNTAX LET GO OBJECT = V-RELEASE>
<SYNTAX LET OBJECT (HELD CARRIED HAVE) GO OBJECT (FIND MANUALLY) = V-RELEASE>

<SYNTAX UNTIE OBJECT = V-UNTIE>
<VERB-SYNONYM UNTIE UNFASTEN UNHOOK>

; <SYNTAX SCREW OBJECT (HELD CARRIED HAVE) IN OBJECT (ON-GROUND IN-ROOM)
	= V-SCREW>
; <SYNTAX SCREW DOWN OBJECT (HELD CARRIED HAVE) IN OBJECT (ON-GROUND IN-ROOM)
	= V-SCREW>
; <SYNTAX SCREW OBJECT (HELD CARRIED HAVE) ON OBJECT (ON-GROUND IN-ROOM)
	= V-SCREW>
; <SYNTAX SCREW DOWN OBJECT (HELD CARRIED HAVE) ON OBJECT (ON-GROUND IN-ROOM)
	= V-SCREW>
; <SYNTAX SCREW IN OBJECT (HELD CARRIED HAVE) ON OBJECT (ON-GROUND IN-ROOM)
	= V-SCREW>
; <SYNTAX SCREW OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (HELD CARRIED HAVE)
	= V-SCREW-WITH>
; <SYNTAX SCREW IN OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (HELD CARRIED HAVE)
	= V-SCREW-WITH>
; <SYNTAX SCREW DOWN OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (HELD CARRIED HAVE)
	= V-SCREW-WITH>
; <VERB-SYNONYM SCREW TIGHTEN>

; <SYNTAX UNSCREW OBJECT (ON-GROUND IN-ROOM HELD CARRIED)
	WITH OBJECT (FIND TOOL) (HELD CARRIED HAVE ; TAKE) = V-UNSCREW>
; <SYNTAX UNSCREW OBJECT (ON-GROUND IN-ROOM HELD CARRIED)
	FROM OBJECT = V-UNSCREW-FROM>
; <SYNTAX UNSCREW OBJECT (ON-GROUND IN-ROOM HELD CARRIED)
	OUT OBJECT = V-UNSCREW-FROM>

<SYNTAX REPAIR OBJECT WITH OBJECT (FIND MANUALLY) (HELD CARRIED HAVE)
	= V-REPAIR>
; <VERB-SYNONYM REPAIR SERVICE>

<SYNTAX FIX OBJECT WITH OBJECT (FIND MANUALLY) (HELD CARRIED HAVE)
	= V-REPAIR>
<SYNTAX FIX UP OBJECT WITH OBJECT (FIND MANUALLY) (HELD CARRIED HAVE)
	= V-REPAIR>

; <SYNTAX WORK ON OBJECT WITH OBJECT (FIND MANUALLY) (HELD CARRIED HAVE)
	 = V-REPAIR>

<SYNTAX REPLACE OBJECT = V-REPLACE>

<SYNTAX RESCUE OBJECT (FIND PERSON) = V-RESCUE>

<SYNTAX RIDE OBJECT = V-RIDE>
<SYNTAX RIDE IN OBJECT = V-RIDE>
<SYNTAX RIDE ON OBJECT = V-RIDE>

<SYNTAX BOW TO OBJECT (FIND PERSON) = V-BOW>
<SYNTAX BOW BEFORE OBJECT (FIND PERSON) = V-BOW>
<VERB-SYNONYM BOW KNEEL GROVEL GENUFLECT>

<SYNTAX SAY OBJECT (FIND LOCATION) = V-SAY>
<SYNTAX SAY TO OBJECT (ON-GROUND IN-ROOM) = V-TELL>
<VERB-SYNONYM SAY TALK SPEAK UTTER PROCLAIM MAYBE>

<SYNTAX CALL OBJECT (FIND LOCATION) = V-YELL>
<SYNTAX CALL TO OBJECT (FIND LIVING) = V-YELL>
<SYNTAX CALL FOR OBJECT (FIND LIVING) = V-REQUEST>

<SYNTAX NAME OBJECT (ON-GROUND IN-ROOM HELD CARRIED) 
	= V-NAME PRE-NAME>
<SYNTAX NAME OBJECT (ON-GROUND IN-ROOM HELD CARRIED) 
	OBJECT = V-NAME PRE-NAME>
<VERB-SYNONYM NAME RENAME>

<SYNTAX CALL OBJECT (ON-GROUND IN-ROOM HELD CARRIED) 
	OBJECT = V-NAME PRE-NAME>

<SYNTAX SEARCH OBJECT = V-SEARCH>
<SYNTAX SEARCH IN OBJECT = V-SEARCH>
<SYNTAX SEARCH FOR OBJECT = V-FIND>
<SYNTAX SEARCH UNDER OBJECT = V-LOOK-UNDER>
<SYNTAX SEARCH THROUGH OBJECT = V-SEARCH>
<VERB-SYNONYM SEARCH RUMMAGE FRISK RANSACK SIFT>

<SYNTAX SHAKE OBJECT WITH OBJECT (FIND MANUALLY) (HELD CARRIED HAVE)
        = V-SHAKE>
<SYNTAX SHAKE OUT OBJECT (HELD CARRIED) = V-EMPTY>
<SYNTAX SHAKE OUT OBJECT (HELD CARRIED HAVE) IN OBJECT = V-EMPTY-INTO>
<SYNTAX SHAKE OUT OBJECT FROM OBJECT (HELD CARRIED HAVE) = V-POUR-FROM>

<SYNTAX JOSTLE OBJECT WITH OBJECT (FIND MANUALLY) (HELD CARRIED HAVE)
        = V-SHAKE>
<VERB-SYNONYM JOSTLE RATTLE>

<SYNTAX SIT OBJECT (FIND LOCATION) (ON-GROUND IN-ROOM) = V-SIT> 
<SYNTAX SIT ON OBJECT (ON-GROUND IN-ROOM) = V-SIT>
<SYNTAX SIT DOWN OBJECT (FIND LOCATION) (ON-GROUND IN-ROOM) = V-SIT>
<SYNTAX SIT IN OBJECT (FIND VEHICLE) 
	(ON-GROUND IN-ROOM) = V-ENTER ; "V-BOARD PRE-BOARD">
<SYNTAX SIT AT OBJECT = V-SIT>
<VERB-SYNONYM SIT SETTLE SQUAT CROUCH>

<SYNTAX SLEEP = V-SLEEP>
<SYNTAX SLEEP IN OBJECT (IN-ROOM ON-GROUND) = V-LIE-DOWN ; V-BOARD>
<SYNTAX SLEEP ON OBJECT (IN-ROOM ON-GROUND) = V-LIE-DOWN ; V-BOARD>
<VERB-SYNONYM SLEEP NAP SNOOZE>

<SYNTAX SLIDE OBJECT = V-MOVE>
<SYNTAX SLIDE OBJECT TO OBJECT = V-PUSH-TO>
<SYNTAX SLIDE OBJECT (HELD CARRIED HAVE ; TAKE) UNDER OBJECT = V-PUT-UNDER>
<SYNTAX SLIDE OBJECT (HELD CARRIED HAVE ; TAKE) IN OBJECT = V-PUT PRE-PUT>
<SYNTAX SLIDE OBJECT (HELD CARRIED HAVE ; TAKE) DOWN OBJECT = V-PUT PRE-PUT>

<SYNTAX SLIDE DOWN OBJECT (FIND LOCATION) = V-CLIMB-DOWN>

<SYNTAX SMELL OBJECT (FIND LOCATION) = V-SMELL>
<VERB-SYNONYM SMELL SNIFF WHIFF INHALE>

<SYNTAX SPIN OBJECT (FIND LOCATION) = V-SPIN>
<VERB-SYNONYM SPIN WHIRL>

<SYNTAX SQUEEZE OBJECT = V-SQUEEZE>
<SYNTAX SQUEEZE OBJECT (HELD CARRIED HAVE) ON OBJECT (ON-GROUND IN-ROOM)
        = V-PUT PRE-PUT>
<VERB-SYNONYM SQUEEZE SQUASH SQUISH CRUSH CRUMPLE>

<SYNTAX STAND OBJECT (FIND LOCATION) = V-STAND>
<SYNTAX STAND UP OBJECT (FIND LOCATION) = V-STAND>
<SYNTAX STAND ON OBJECT = V-STAND-ON>
<SYNTAX STAND IN OBJECT = V-ENTER>
<SYNTAX STAND UNDER OBJECT = V-STAND-UNDER>
<VERB-SYNONYM STAND RISE>

<SYNTAX DUCK = V-DUCK>
<SYNTAX DUCK UNDER OBJECT = V-STAND-UNDER>

<SYNTAX SWIM OBJECT (FIND LOCATION) = V-SWIM>
<SYNTAX SWIM DOWN OBJECT (FIND LOCATION) = V-DIVE>
<SYNTAX SWIM UP OBJECT (FIND LOCATION) = V-SWIM>
<SYNTAX SWIM IN OBJECT = V-SWIM>
<SYNTAX SWIM TO OBJECT = V-SWIM>
<SYNTAX SWIM THROUGH OBJECT = V-SWIM>
<SYNTAX SWIM OVER OBJECT = V-SWIM>
<SYNTAX SWIM UNDER OBJECT = V-DIVE>
<VERB-SYNONYM SWIM BATHE WADE>

<SYNTAX DIVE OBJECT (FIND LOCATION) = V-DIVE>
<SYNTAX DIVE DOWN OBJECT (FIND LOCATION) = V-DIVE>
<SYNTAX DIVE IN OBJECT (FIND LOCATION) = V-DIVE>
<SYNTAX DIVE UNDER OBJECT (FIND LOCATION) = V-DIVE>
<SYNTAX DIVE OVER OBJECT = V-LEAP>

<SYNTAX SWING OBJECT (HELD CARRIED HAVE) = V-SWING>
<SYNTAX SWING OBJECT (HELD CARRIED HAVE)
	AT OBJECT (FIND MONSTER) (ON-GROUND IN-ROOM) = V-SWING>

<SYNTAX SWING ON OBJECT = V-CLIMB-ON>

<SYNTAX TAKE OBJECT (FIND TAKEABLE) (ON-GROUND IN-ROOM MANY) 
	= V-TAKE PRE-TAKE>
<SYNTAX TAKE UP OBJECT (FIND LOCATION) = V-RAISE>
<SYNTAX TAKE DOWN OBJECT (FIND LOCATION) = V-LOWER>
<SYNTAX TAKE OBJECT (FIND TAKEABLE) (IN-ROOM CARRIED MANY)
	OUT OBJECT = V-TAKE PRE-TAKE>
<SYNTAX TAKE OBJECT (FIND TAKEABLE) (IN-ROOM CARRIED MANY)
	OFF OBJECT = V-TAKE PRE-TAKE>
<SYNTAX TAKE OBJECT (FIND TAKEABLE) (IN-ROOM CARRIED MANY)
	FROM OBJECT = V-TAKE PRE-TAKE>
<SYNTAX TAKE OBJECT (FIND TAKEABLE) (IN-ROOM CARRIED MANY)
	IN OBJECT = V-TAKE PRE-TAKE>
<SYNTAX TAKE OBJECT (FIND TAKEABLE) (IN-ROOM CARRIED MANY)
	ON OBJECT = V-TAKE PRE-TAKE>
<SYNTAX TAKE OBJECT (FIND TAKEABLE) (IN-ROOM CARRIED MANY)
	WITH OBJECT (HELD CARRIED HAVE) = V-TAKE-WITH>
<SYNTAX TAKE APART OBJECT (ON-GROUND IN-ROOM) = V-OPEN>
<VERB-SYNONYM TAKE GRAB KEEP CATCH CARRY SEIZE STEAL SNATCH>

<SYNTAX TAKE OFF OBJECT (FIND LOCATION) (HELD CARRIED) = V-TAKE-OFF>

<SYNTAX REMOVE OBJECT (FIND WORN) (HELD CARRIED) = V-TAKE-OFF>
<SYNTAX REMOVE OBJECT (FIND TAKEABLE) (ON-GROUND IN-ROOM MANY)
	FROM OBJECT = V-TAKE PRE-TAKE>
<SYNTAX REMOVE OBJECT (FIND TAKEABLE) (ON-GROUND IN-ROOM MANY)
        ON OBJECT = V-TAKE PRE-TAKE>
<SYNTAX REMOVE OBJECT (FIND TAKEABLE) (ON-GROUND IN-ROOM MANY)
        IN OBJECT = V-TAKE PRE-TAKE>
<SYNTAX REMOVE OBJECT (FIND TAKEABLE) WITH OBJECT (HELD CARRIED HAVE)
        = V-TAKE-WITH> 

<SYNTAX HOLD OBJECT (FIND TAKEABLE) (ON-GROUND IN-ROOM MANY) 
	= V-TAKE PRE-TAKE>
<SYNTAX HOLD ON OBJECT (FIND TAKEABLE) (ON-GROUND IN-ROOM) = V-TAKE PRE-TAKE>
<SYNTAX HOLD UP OBJECT (FIND LOCATION) (HELD CARRIED HAVE) = V-RAISE>
<SYNTAX HOLD OBJECT (HELD CARRIED HAVE) IN OBJECT = V-PUT PRE-PUT>
<SYNTAX HOLD OBJECT (HELD CARRIED HAVE) OVER OBJECT = V-HOLD-OVER>
<SYNTAX HOLD OBJECT (HELD CARRIED HAVE) ON OBJECT = V-TOUCH-TO>
<SYNTAX HOLD OBJECT (HELD CARRIED HAVE) AGAINST OBJECT = V-TOUCH-TO>
<SYNTAX HOLD DOWN OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-LOWER>
<SYNTAX HOLD APART OBJECT (ON-GROUND IN-ROOM) = V-OPEN>

<SYNTAX GET OBJECT (FIND TAKEABLE) (ON-GROUND IN-ROOM MANY) 
	= V-TAKE PRE-TAKE>
<SYNTAX GET IN OBJECT (FIND LOCATION) (ON-GROUND IN-ROOM) = V-ENTER>
<SYNTAX GET OUT OBJECT (FIND LOCATION) (ON-GROUND IN-ROOM) = V-EXIT>
<SYNTAX GET ON OBJECT (ON-GROUND IN-ROOM) = V-CLIMB-ON>
<SYNTAX GET UP OBJECT (FIND LOCATION) (ON-GROUND IN-ROOM) = V-CLIMB-UP>
<SYNTAX GET DOWN OBJECT (FIND LOCATION) (ON-GROUND IN-ROOM) = V-CLIMB-DOWN>
<SYNTAX GET UNDER OBJECT (ON-GROUND IN-ROOM) = V-STAND-UNDER>
<SYNTAX GET BEHIND OBJECT (ON-GROUND IN-ROOM) = V-WALK-AROUND>
<SYNTAX GET OBJECT (FIND TAKEABLE) (IN-ROOM CARRIED MANY)
	OUT OBJECT = V-TAKE PRE-TAKE>
<SYNTAX GET OBJECT (FIND TAKEABLE) (IN-ROOM CARRIED MANY)
	OFF OBJECT = V-TAKE PRE-TAKE>
<SYNTAX GET OBJECT (FIND TAKEABLE) (IN-ROOM CARRIED MANY)
	FROM OBJECT = V-TAKE PRE-TAKE>
<SYNTAX GET OBJECT (FIND TAKEABLE) (IN-ROOM CARRIED MANY)
	IN OBJECT = V-TAKE PRE-TAKE>
<SYNTAX GET OBJECT (FIND TAKEABLE) (IN-ROOM CARRIED MANY)
	ON OBJECT = V-TAKE PRE-TAKE>
<SYNTAX GET OBJECT (FIND TAKEABLE) (IN-ROOM CARRIED MANY)
	WITH OBJECT (HELD CARRIED HAVE) = V-TAKE-WITH>
<SYNTAX GET OFF OBJECT (FIND LOCATION) = V-EXIT>
<SYNTAX GET AWAY OBJECT (FIND LOCATION) = V-ESCAPE>
<SYNTAX GET TO OBJECT = V-WALK-TO>
<SYNTAX GET BACK OBJECT (FIND LOCATION) = V-WALK-TO>
<SYNTAX GET OBJECT (ON-GROUND IN-ROOM) OBJECT = V-SGET-FOR>
<SYNTAX GET OBJECT FOR OBJECT (ON-GROUND IN-ROOM) = V-GET-FOR>
<SYNTAX GET OBJECT TO OBJECT (ON-GROUND IN-ROOM) = V-GET-FOR>

<SYNTAX BRING OBJECT TO OBJECT (ON-GROUND IN-ROOM) = V-GET-FOR>
<SYNTAX BRING BACK OBJECT TO OBJECT (ON-GROUND IN-ROOM) = V-GET-FOR>
<SYNTAX BRING OBJECT FOR OBJECT (ON-GROUND IN-ROOM) = V-GET-FOR>
<SYNTAX BRING OBJECT (ON-GROUND IN-ROOM) OBJECT = V-SGET-FOR>

<SYNTAX BOARD OBJECT (ON-GROUND IN-ROOM) = V-ENTER>
<VERB-SYNONYM BOARD MOUNT>

<SYNTAX EMBARK OBJECT (FIND LOCATION) = V-ENTER>
<SYNTAX EMBARK ON OBJECT = V-ENTER>

<SYNTAX DISEMBARK OBJECT (FIND LOCATION) = V-EXIT>
<SYNTAX DISEMBARK FROM OBJECT = V-EXIT>
<SYNTAX DISEMBARK OUT OBJECT = V-EXIT>

<SYNTAX TASTE OBJECT = V-TASTE>
<VERB-SYNONYM TASTE LICK>

<SYNTAX TELL OBJECT (FIND PERSON) (IN-ROOM) = V-TELL>
<SYNTAX TELL OBJECT (FIND PERSON) (IN-ROOM) ABOUT OBJECT = V-TELL-ABOUT>
<VERB-SYNONYM TELL ADVISE INFORM>

<SYNTAX THANK OBJECT = V-THANK>
<SYNTAX THANK = V-THANK>
<VERB-SYNONYM THANK THANKS>

<SYNTAX THROW OBJECT (HELD MANY CARRIED HAVE)
	AT OBJECT (ON-GROUND IN-ROOM) = V-THROW PRE-THROW>
<SYNTAX THROW OBJECT (HELD MANY CARRIED HAVE)
	TO OBJECT (ON-GROUND IN-ROOM) = V-THROW PRE-THROW>
<SYNTAX THROW OBJECT (HELD MANY CARRIED HAVE) 
	OFF OBJECT = V-THROW-OVER PRE-THROW-OVER>
<SYNTAX THROW OBJECT (HELD MANY CARRIED HAVE) 
	OVER OBJECT = V-THROW-OVER PRE-THROW-OVER>
<SYNTAX THROW OBJECT (HELD MANY CARRIED HAVE)
	THROUGH OBJECT (ON-GROUND IN-ROOM) = V-PUT PRE-PUT>
<SYNTAX THROW OBJECT (HELD MANY CARRIED HAVE) DOWN OBJECT
	(ON-GROUND IN-ROOM) = V-PUT PRE-PUT>
<SYNTAX THROW OBJECT (HELD MANY CARRIED HAVE) IN OBJECT
	(ON-GROUND IN-ROOM) = V-PUT PRE-PUT>
<SYNTAX THROW OBJECT (HELD MANY CARRIED HAVE) ON OBJECT
	(ON-GROUND IN-ROOM) = V-PUT PRE-PUT>
<SYNTAX THROW AWAY OBJECT (HELD MANY CARRIED HAVE) = V-DROP>
<SYNTAX THROW OBJECT (ON-GROUND IN-ROOM) OBJECT (HELD MANY CARRIED HAVE)
	= V-STHROW>
<VERB-SYNONYM THROW TOSS HURL CHUCK FLING PITCH>

<SYNTAX TIE OBJECT = V-TIE>
<SYNTAX TIE OBJECT TO OBJECT = V-TIE>
<SYNTAX TIE UP OBJECT (FIND PERSON) (ON-GROUND IN-ROOM) WITH OBJECT
	(FIND MANUALLY) (ON-GROUND IN-ROOM HELD CARRIED HAVE) = V-TIE-UP>
<VERB-SYNONYM TIE FASTEN SECURE>

<SYNTAX TOUCH OBJECT = V-TOUCH>
<SYNTAX TOUCH OBJECT (HELD CARRIED HAVE) TO OBJECT = V-TOUCH-TO>
<SYNTAX TOUCH OBJECT (HELD CARRIED HAVE) AGAINST OBJECT = V-TOUCH-TO>
<SYNTAX TOUCH TOGETHER OBJECT (HELD CARRIED HAVE) WITH OBJECT = V-TOUCH-TO>
<SYNTAX TOUCH OBJECT (HELD CARRIED HAVE) TOGETHER OBJECT = V-TOUCH-TO>
<SYNTAX TOUCH OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-STOUCH-TO>

<SYNTAX DISTURB OBJECT = V-TOUCH>
<SYNTAX DISTURB OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-STOUCH-TO>

<SYNTAX PROBE OBJECT = V-EXAMINE PRE-EXAMINE>
<SYNTAX PROBE OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-STOUCH-TO>

<SYNTAX PET OBJECT = V-TOUCH>
<VERB-SYNONYM PET PAT CUDDLE>

<SYNTAX FEEL OBJECT = V-TOUCH>
<SYNTAX FEEL IN OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-REACH-IN>

<SYNTAX TURN OBJECT (FIND LOCATION) = V-SPIN>
<SYNTAX TURN OBJECT WITH OBJECT (FIND MANUALLY) 
	(HELD CARRIED HAVE ; TAKE) = V-TURN>
<SYNTAX TURN THROUGH OBJECT = V-READ>
<SYNTAX TURN TO OBJECT = V-TURN-TO>
<SYNTAX TURN ON OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-LAMP-ON>
<SYNTAX TURN OFF OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-LAMP-OFF>
<SYNTAX TURN AROUND OBJECT (FIND LOCATION) = V-SPIN>
<SYNTAX TURN OVER OBJECT = V-SPIN>
<SYNTAX TURN DOWN OBJECT = V-REFUSE>
<SYNTAX TURN BACK OBJECT (FIND LOCATION) = V-SPIN>
<SYNTAX TURN OBJECT (IN-ROOM ON-GROUND) TO OBJECT = V-POINT-AT PRE-POINT-AT>
<SYNTAX TURN OBJECT (IN-ROOM ON-GROUND) OBJECT = V-POINT-AT PRE-POINT-AT>
<VERB-SYNONYM TURN ROTATE FLIP>

<SYNTAX CRANK OBJECT (FIND LOCATION) = V-CRANK>

<SYNTAX START OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-LAMP-ON>
<SYNTAX START OBJECT (HELD CARRIED ON-GROUND IN-ROOM)
	WITH OBJECT (HELD CARRIED HAVE) = V-LAMP-ON>
<SYNTAX START UP OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-LAMP-ON>
<SYNTAX START UP OBJECT (HELD CARRIED ON-GROUND IN-ROOM)
	WITH OBJECT (HELD CARRIED HAVE) = V-LAMP-ON>

<SYNTAX STOP OBJECT (FIND LOCATION) (HELD CARRIED ON-GROUND IN-ROOM)
	= V-LAMP-OFF>
<VERB-SYNONYM STOP HALT>

<SYNTAX UNLOCK OBJECT (ON-GROUND IN-ROOM) 
	WITH OBJECT (FIND TOOL) (HELD CARRIED HAVE ; TAKE) = V-UNLOCK>

; <SYNTAX UNTIE OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-UNTIE>
; <SYNTAX UNTIE OBJECT (ON-GROUND IN-ROOM)
          WITH OBJECT (FIND MANUALLY) (HAVE) = V-UNLOCK>
; <SYNTAX UNTIE OBJECT (ON-GROUND IN-ROOM HELD CARRIED) 
	  FROM OBJECT = V-UNLOCK>
; <VERB-SYNONYM UNTIE FREE UNFASTEN UNATTACH UNHOOK RELEASE UNDO>

<SYNTAX USE OBJECT = V-USE>
<VERB-SYNONYM USE EMPLOY EXPLOIT OPERATE>

<SYNTAX WAIT = V-WAIT>
<SYNTAX WAIT FOR OBJECT = V-WAIT-FOR>
<VERB-SYNONYM WAIT Z>

<SYNTAX REST = V-WAIT>
<VERB-SYNONYM REST LOITER PAUSE>

<SYNTAX WAKE OBJECT (FIND LOCATION) = V-ALARM>
<SYNTAX WAKE UP OBJECT (FIND LOCATION) = V-ALARM>
<VERB-SYNONYM WAKE AWAKE AWAKEN ROUSE>

<SYNTAX SCARE OBJECT (FIND LIVING) = V-ALARM>
<VERB-SYNONYM SCARE AROUSE STARTLE SURPRISE FRIGHTEN> 

<SYNTAX WALK = V-WALK-AROUND>
<SYNTAX WALK OBJECT = V-WALK>
<SYNTAX WALK IN OBJECT (FIND LOCATION) = V-ENTER>
<SYNTAX WALK OUT OBJECT (FIND LOCATION) = V-EXIT>
<SYNTAX WALK OFF OBJECT (FIND LOCATION) = V-EXIT>
<SYNTAX WALK ON OBJECT = V-STAND-ON>
<SYNTAX WALK OVER OBJECT = V-CROSS>
<SYNTAX WALK THROUGH OBJECT = V-THROUGH>
<SYNTAX WALK AROUND OBJECT (FIND LOCATION) = V-WALK-AROUND>
<SYNTAX WALK BEHIND OBJECT = V-WALK-AROUND>
<SYNTAX WALK UNDER OBJECT = V-STAND-UNDER>
<SYNTAX WALK UP OBJECT (FIND LOCATION) (ON-GROUND IN-ROOM) = V-CLIMB-UP>
<SYNTAX WALK DOWN OBJECT (FIND LOCATION) (ON-GROUND IN-ROOM) = V-CLIMB-DOWN>
<SYNTAX WALK TO OBJECT = V-WALK-TO>
<SYNTAX WALK FROM OBJECT = V-ESCAPE>
<SYNTAX WALK AWAY OBJECT (FIND LOCATION) = V-ESCAPE>
<SYNTAX WALK PAST OBJECT (FIND LOCATION) = V-ESCAPE>
<VERB-SYNONYM WALK PROCEED STEP TRUDGE HIKE TRAMP CRAWL RUN JOG
	      SKIP HOP ADVANCE STROLL>

<SYNTAX APPROACH OBJECT = V-WALK-TO>

<SYNTAX GO = V-WALK-AROUND>
<SYNTAX GO OBJECT = V-WALK>
<SYNTAX GO IN OBJECT (FIND LOCATION) = V-ENTER>
<SYNTAX GO OUT OBJECT (FIND LOCATION) = V-EXIT>
<SYNTAX GO ON OBJECT = V-STAND-ON>
<SYNTAX GO OVER OBJECT = V-CROSS>
<SYNTAX GO THROUGH OBJECT = V-THROUGH>
<SYNTAX GO AROUND OBJECT (FIND LOCATION) = V-WALK-AROUND>
<SYNTAX GO BEHIND OBJECT = V-WALK-AROUND>
<SYNTAX GO UNDER OBJECT = V-STAND-UNDER>
<SYNTAX GO UP OBJECT (FIND LOCATION) (ON-GROUND IN-ROOM) = V-CLIMB-UP>
<SYNTAX GO DOWN OBJECT (FIND LOCATION) (ON-GROUND IN-ROOM) = V-CLIMB-DOWN>
<SYNTAX GO TO OBJECT = V-WALK-TO>
<SYNTAX GO AWAY OBJECT (FIND LOCATION) = V-ESCAPE>
<SYNTAX GO FROM OBJECT = V-ESCAPE>
<SYNTAX GO BACK OBJECT (FIND LOCATION) = V-WALK-TO>

<SYNTAX RETURN OBJECT (FIND LOCATION) = V-WALK-TO>
<SYNTAX RETURN TO OBJECT = V-WALK-TO>

<SYNTAX WAVE OBJECT (HELD CARRIED HAVE) = V-SWING>
<SYNTAX WAVE AROUND OBJECT (HELD CARRIED HAVE) = V-SWING>
<SYNTAX WAVE OBJECT (HELD CARRIED HAVE) AT OBJECT (ON-GROUND IN-ROOM)
	= V-POINT-AT PRE-POINT-AT>
<SYNTAX WAVE OBJECT (HELD CARRIED HAVE) OVER OBJECT (ON-GROUND IN-ROOM)
	= V-POINT-AT PRE-POINT-AT>
<SYNTAX WAVE OBJECT (HELD CARRIED HAVE) AROUND OBJECT (ON-GROUND IN-ROOM)
	= V-POINT-AT PRE-POINT-AT>
<SYNTAX WAVE AT OBJECT (FIND PERSON) = V-WAVE-AT>
<SYNTAX WAVE TO OBJECT (FIND PERSON) = V-WAVE-AT> 

<SYNTAX NOD AT OBJECT (FIND PERSON) = V-WAVE-AT>
<SYNTAX NOD TO OBJECT (FIND PERSON) = V-WAVE-AT>
<VERB-SYNONYM NOD SMILE GRIN SNEER BECKON>

<SYNTAX WEAR OBJECT = V-WEAR>
<VERB-SYNONYM WEAR DON>

<SYNTAX WHAT OBJECT = V-WHAT>
<SYNTAX WHAT ABOUT OBJECT = V-WHAT>
<VERB-SYNONYM WHAT WHATS WHAT\'S>

<SYNTAX WHERE OBJECT = V-WHERE>
<VERB-SYNONYM WHERE WHERES WHERE\'S>

<SYNTAX WHO OBJECT = V-WHO>
<VERB-SYNONYM WHO WHOS WHO\'S>

<SYNTAX WIND OBJECT = V-WIND>
<SYNTAX WIND UP OBJECT = V-WIND>
<SYNTAX WIND OBJECT (HELD CARRIED HAVE) AROUND OBJECT (ON-GROUND IN-ROOM)
	= V-WRAP-AROUND>
<SYNTAX WIND OBJECT (ON-GROUND IN-ROOM) IN OBJECT (HELD CARRIED HAVE)
	= V-SWRAP>
<SYNTAX WIND UP OBJECT (ON-GROUND IN-ROOM) IN OBJECT (HELD CARRIED HAVE)
	= V-SWRAP>

<SYNTAX YELL OBJECT (FIND LOCATION) = V-YELL>
<SYNTAX YELL AT OBJECT = V-YELL>
<SYNTAX YELL TO OBJECT = V-YELL>
<SYNTAX YELL FOR OBJECT = V-REQUEST>
<VERB-SYNONYM YELL SCREAM SHOUT HOWL>

<SYNTAX LAUGH = V-LAUGH>
<SYNTAX LAUGH AT OBJECT = V-LAUGH>
<VERB-SYNONYM LAUGH CHUCKLE>

<SYNTAX INSULT OBJECT = V-LAUGH>
<VERB-SYNONYM INSULT OFFEND>

<SYNTAX YES OBJECT (FIND LOCATION) = V-HELLO>
<VERB-SYNONYM YES Y OK OKAY SURE YUP 
	      NO NAY NEGATIVE NOPE>

; <SYNTAX NO = V-NO>
; <VERB-SYNONYM NO NAY NEGATIVE NOPE NAW>

<SYNTAX MELT OBJECT (HELD CARRIED HAVE) = V-MELT>

<SYNTAX DRESS OBJECT (FIND LOCATION) = V-DRESS>

<SYNTAX UNDRESS OBJECT (FIND LOCATION) = V-UNDRESS>
<VERB-SYNONYM UNDRESS DISROBE STRIP>

<SYNTAX ESCAPE OBJECT (FIND LOCATION) = V-ESCAPE>
<SYNTAX ESCAPE FROM OBJECT (ON-GROUND IN-ROOM) = V-ESCAPE>
<SYNTAX ESCAPE AWAY OBJECT (FIND LOCATION) = V-ESCAPE>
<VERB-SYNONYM ESCAPE FLEE>

<SYNTAX WIELD OBJECT (HELD CARRIED HAVE) = V-WIELD>

<SYNTAX SCRATCH OBJECT = V-SCRATCH>
<SYNTAX SCRATCH OBJECT (HELD CARRIED HAVE) ON OBJECT = V-SCRAPE-ON>
<SYNTAX SCRATCH OBJECT (HELD CARRIED HAVE) IN OBJECT = V-SCRAPE-ON>
<SYNTAX SCRATCH OBJECT (HELD CARRIED HAVE) OVER OBJECT = V-SCRAPE-ON>
<SYNTAX SCRATCH OBJECT (HELD CARRIED HAVE) AGAINST OBJECT = V-SCRAPE-ON>
<SYNTAX SCRATCH OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-STOUCH-TO>
<VERB-SYNONYM SCRATCH SCRAPE CARVE>

<SYNTAX ITCH OBJECT = V-SCRATCH>

<SYNTAX LURK OBJECT (FIND LOCATION) = V-LURK>
<SYNTAX LURK AROUND OBJECT (FIND LOCATION) = V-LURK>
<SYNTAX SLAVER = V-LURK>
<SYNTAX SLAVER ON OBJECT = V-LURK>

<SYNTAX WRITE OBJECT ON OBJECT = V-WRITE-ON>
<SYNTAX WRITE OBJECT IN OBJECT = V-WRITE-ON>
<SYNTAX WRITE OBJECT OVER OBJECT = V-WRITE-ON>
<SYNTAX WRITE OBJECT AROUND OBJECT = V-WRITE-ON>
<SYNTAX WRITE OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-WRITE-WITH>
<SYNTAX WRITE ON OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-WRITE-WITH>
<VERB-SYNONYM WRITE DRAW INSCRIBE TRACE>

<SYNTAX ZAP OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (HELD CARRIED HAVE)
	= V-ZAP-WITH>
<SYNTAX ZAP OBJECT (HELD CARRIED HAVE) AT OBJECT (ON-GROUND IN-ROOM)
	= V-FIRE-AT>

<SYNTAX FIRE OBJECT (HELD CARRIED HAVE) AT OBJECT (ON-GROUND IN-ROOM)
	= V-FIRE-AT>
<SYNTAX FIRE OFF OBJECT (HELD CARRIED HAVE) AT OBJECT (ON-GROUND IN-ROOM)
	= V-FIRE-AT>
<SYNTAX FIRE AT OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (HELD CARRIED HAVE)
	= V-SFIRE-AT>
<SYNTAX FIRE OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (HELD CARRIED HAVE)
	= V-SFIRE-AT>
<VERB-SYNONYM FIRE SHOOT>

<SYNTAX PLANT OBJECT (HELD CARRIED HAVE) = V-PLANT>

<SYNTAX UPROOT OBJECT = V-UPROOT>

<SYNTAX UNMAKE OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-UNMAKE>
<VERB-SYNONYM UNMAKE FROTZ DISPEL>

<SYNTAX SPELLS = V-SPELLS>

<SYNTAX SMEE = V-MAGIC>
<VERB-SYNONYM SMEE YABBA BOK SQUIRP STELLA BLARN
	      PROSSER YQUEM WATKIN JUKES MACUGA LIGHTNING YOUTH>
