

; STRINGS ARE DEFINED HERE

STRBEG::

	.GSTR STR?1,"DEC-20"
	.GSTR STR?2,"Apple //e"
	.GSTR STR?3,"Macintosh"
	.GSTR STR?4,"Amiga"
	.GSTR STR?5,"Atari ST"
	.GSTR STR?6,"IBM/MS-DOS"
	.GSTR STR?7,"Commodore 128"
	.GSTR STR?8,"C64"
	.GSTR STR?9,"Apple //c"
	.GSTR STR?10,"Apple //gs"
	.GSTR STR?11,"Tandy Color Computer"
	.GSTR STR?12,"EN"
	.GSTR STR?13,"ST"
	.GSTR STR?14,"DX"
	.GSTR STR?15,"IQ"
	.GSTR STR?16,"CM"
	.GSTR STR?17,"LK"
	.GSTR STR?18,"AC"
	.GSTR STR?19," F1"
	.GSTR STR?20," F2"
	.GSTR STR?21," F3"
	.GSTR STR?22," F4"
	.GSTR STR?23," F5"
	.GSTR STR?24," F6"
	.GSTR STR?25," F7"
	.GSTR STR?26," F8"
	.GSTR STR?27," F9"
	.GSTR STR?28,"F10"
	.GSTR STR?29,"[1]"
	.GSTR STR?30,"[2]"
	.GSTR STR?31,"[3]"
	.GSTR STR?32,"[4]"
	.GSTR STR?33,"[5]"
	.GSTR STR?34,"[6]"
	.GSTR STR?35,"[7]"
	.GSTR STR?36,"[8]"
	.GSTR STR?37,"[9]"
	.GSTR STR?38,"[0]"
	.GSTR STR?39,"unusual"
	.GSTR STR?40,"interesting"
	.GSTR STR?41,"extraordinary"
	.GSTR STR?42,"special"
	.GSTR STR?43,"n't do anything useful"
	.GSTR STR?44," accomplish nothing"
	.GSTR STR?45," have no desirable effect"
	.GSTR STR?46,"n't be very productive"
	.GSTR STR?47," serve no purpose"
	.GSTR STR?48," be pointless"
	.GSTR STR?49,"That's impossible"
	.GSTR STR?50,"What a ridiculous concept"
	.GSTR STR?51,"You can't be serious"
	.GSTR STR?52,"firm"
	.GSTR STR?53,"permanent"
	.GSTR STR?54,"immovab"
	.GSTR STR?55,"secure"
	.GSTR STR?56,"attached"
	.GSTR STR?57,"affixed"
	.GSTR STR?58,"There's no point in doing that"
	.GSTR STR?59,"That would be pointless"
	.GSTR STR?60,"That's a pointless thing to do"
	.GSTR STR?61,"puzzl"
	.GSTR STR?62,"bewilder"
	.GSTR STR?63,"confus"
	.GSTR STR?64,"perplex"
	.GSTR STR?65,"The word """
	.GSTR STR?66,""" isn't in the vocabulary that you can use."
	.GSTR STR?67,"You don't need to use the word """
	.GSTR STR?68,""" to complete this story."
	.GSTR STR?69,"This story doesn't recognize the word """
	.GSTR STR?70,"."""
	.GSTR STR?71," isn't likely"
	.GSTR STR?72," seems doubtful"
	.GSTR STR?73," seems unlikely"
	.GSTR STR?74,"'s unlikely"
	.GSTR STR?75,"'s not likely"
	.GSTR STR?76,"'s doubtful"
	.GSTR STR?89," Display Mode "
	.GSTR STR?90," Descriptions "
	.GSTR STR?91," Transcripting "
	.GSTR STR?92," Status Notify "
	.GSTR STR?93," Map View "
	.GSTR STR?94," Display Priority "
	.GSTR STR?95," Combat Monitor "
	.GSTR STR?96," Restore Defaults "
	.GSTR STR?97," Exit "
	.GSTR STR?98,"Lucky  "
	.GSTR STR?99,"Tank   "
	.GSTR STR?100,"Muscles"
	.GSTR STR?101,"Nimble "
	.GSTR STR?102,"Genius "
	.GSTR STR?103,"Saint  "
	.GSTR STR?104,"Peasant"
	.GSTR STR?105,"Novice"
	.GSTR STR?106,"Cheater"
	.GSTR STR?107,"endurance"
	.GSTR STR?108,"strength"
	.GSTR STR?109,"dexterity"
	.GSTR STR?110,"intelligence"
	.GSTR STR?111,"compassion"
	.GSTR STR?112,"luck"
	.GSTR STR?113,"armor class"
	.GSTR STR?114,"experience"
	.GSTR STR?115,"You sense a presence lurking in the darkness"
	.GSTR STR?116,"A presence lurks in the darkness close at hand"
	.GSTR STR?117,"Something is lurking in the darkness nearby"
	.GSTR STR?118,"yard improvements"
	.GSTR STR?119,"weaponry"
	.GSTR STR?120,"armor"
	.GSTR STR?121,"humility and self-effacement"
	.GSTR STR?122,"transportation"
	.GSTR STR?123,"Ruins"
	.GSTR STR?124,"Bridge"
	.GSTR STR?125,"Forest"
	.GSTR STR?126,"Town"
	.GSTR STR?127,"City"
	.GSTR STR?128,"Seashore"
	.GSTR STR?129,"Roadway"
	.GSTR STR?130,"Fields"
	.GSTR STR?131,"Village"
	.GSTR STR?132,"Castle"
	.GSTR STR?133,"Mist"
	.GSTR STR?134,"Jungle"
	.GSTR STR?135,"Seaport"
	.GSTR STR?136,"Mountainside"
	.GSTR STR?137,"wraith of colored light"
	.GSTR STR?138,"brief chord of music"
	.GSTR STR?139,"whiff of random odors"
	.GSTR STR?140,"puff of tasty flavors"
	.GSTR STR?141,"vague itchiness"
	.GSTR STR?142,"strange sense of urgency"
	.GSTR STR?143,"eyes sting"
	.GSTR STR?144,"ears ring"
	.GSTR STR?145,"nose tickle"
	.GSTR STR?146,"mouth water"
	.GSTR STR?147,"skin crawl"
	.GSTR STR?148,"pulse race"
	.GSTR STR?149," wiggles its antennae"
	.GSTR STR?150," looks up at you inquisitively"
	.GSTR STR?151," arches its back"
	.GSTR STR?152," silently explores "
	.GSTR STR?153," crawls across "
	.GSTR STR?154," wiggles its way around "
	.GSTR STR?155," explores the rim of the goblet"
	.GSTR STR?156," slowly opens and closes its wings"
	.GSTR STR?157," darts around your head"
	.GSTR STR?158," lights on your nose, then flutters off"
	.GSTR STR?159," lands on your hand, then darts away"
	.GSTR STR?160," hovers around "
	.GSTR STR?161," seems interested in "
	.GSTR STR?162," is fluttering close to "
	.GSTR STR?163," whisper among themselves"
	.GSTR STR?164," shuffle around uncertainly"
	.GSTR STR?165," seem to be regrouping"
	.GSTR STR?166," shuffle around disconsolately"
	.GSTR STR?167," sing carols of mourning"
	.GSTR STR?168," shake their ornaments with frustration"
	.GSTR STR?169," skulk about the pasture's edge"
	.GSTR STR?170," shout something incoherent"
	.GSTR STR?171," call out to one another"
	.GSTR STR?172," rubs up against your leg"
	.GSTR STR?173," mews sweetly"
	.GSTR STR?174," plays at your feet"
	.GSTR STR?175," looks up at you and mews"
	.GSTR STR?176," is moving about your feet"
	.GSTR STR?177," purrs in the darkness"
	.GSTR STR?178," settles comfortably"
	.GSTR STR?179," purrs and nudges about"
	.GSTR STR?180," squirms around"
	.GSTR STR?181," is acting a bit restless"
	.GSTR STR?182," shifts its position in your arms"
	.GSTR STR?183," fidgets about uncomfortably"
	.GSTR STR?184," snores gently"
	.GSTR STR?185," fidgets in its sleep"
	.GSTR STR?186," yawns without waking up"
	.GSTR STR?187," fidgets nervously"
	.GSTR STR?188," whimpers with fear"
	.GSTR STR?189," mews anxiously"
	.GSTR STR?190," sniffs the ground suspiciously"
	.GSTR STR?191," whines anxiously, pawing at the ground"
	.GSTR STR?192," is snuffling around underfoot"
	.GSTR STR?193,"screech"
	.GSTR STR?194,"squawk"
	.GSTR STR?195,"croak"
	.GSTR STR?196,"fear"
	.GSTR STR?197,"anxiety"
	.GSTR STR?198,"terror"
	.GSTR STR?199,"anger"
	.GSTR STR?200,"rage"
	.GSTR STR?201,"fury"
	.GSTR STR?202," snaps at you with its beak"
	.GSTR STR?203," screeches pitifully"
	.GSTR STR?204," flutters its good wing back and forth"
	.GSTR STR?205," cries out with pain"
	.GSTR STR?206," limps about in a helpless circle"
	.GSTR STR?207," scratches the ground with its claws"
	.GSTR STR?208," emits a dry croak of contentment"
	.GSTR STR?209," watches you with a sharp, beady eye"
	.GSTR STR?210," screeches at the sky"
	.GSTR STR?211," flutters about restlessly"
	.GSTR STR?212," eyeing you expectantly"
	.GSTR STR?213," sharpening its beak"
	.GSTR STR?214," fluttering its wings"
	.GSTR STR?215," peers at the ground below"
	.GSTR STR?216," circles patiently"
	.GSTR STR?217," beats its powerful wings"
	.GSTR STR?218," turns to look at you"
	.GSTR STR?219,"your mouth gags with the taste of orcish nightsoil"
	.GSTR STR?220,"the stench of burning fish cakes makes you stagger"
	.GSTR STR?221,"hundreds of imaginary spiders crawl across your skin"
	.GSTR STR?222,"a syrupy arrangement of ""Born in the GUE"" pounds in your ears"
	.GSTR STR?223,"the raw glare of a disco strobe sends you reeling"
	.GSTR STR?224," tries to climb higher, but can't quite manage it"
	.GSTR STR?225," snorts at you angrily, trying to climb higher"
	.GSTR STR?226," angrily paws the bottom of the maw"
	.GSTR STR?227,"Woe! Woe is us"
	.GSTR STR?228,"Who will save us? O woe"
	.GSTR STR?229,"O woe is us, woe"
	.GSTR STR?230,"Will no one answer our prayers? Woe"
	.GSTR STR?231," hobbles out of your reach"
	.GSTR STR?232," backs away from you"
	.GSTR STR?233," won't let you near"
	.GSTR STR?234,"Plover the River and Frotz the Woods"
	.GSTR STR?235,"Winter Bozbarland"
	.GSTR STR?236,"Dwaarnyn the Dark-Nosed Ur-Grue"
	.GSTR STR?237,"I'm Dreaming of a Black Cavern"
	.GSTR STR?238,"Good King Flathead"
	.GSTR STR?239,"Dornbeasts Roasting on an Open Fire"
	.GSTR STR?240," sing a few verses of """
	.GSTR STR?241," hum the chorus from """
	.GSTR STR?242," begin crooning """
	.GSTR STR?243," blink their lights"
	.GSTR STR?244," swish their tinsel"
	.GSTR STR?245," rattle their ornaments"
	.GSTR STR?246," does his best to ignore you"
	.GSTR STR?247," busies himself around the kitchen"
	.GSTR STR?248," glances up at you and scowls"
	.GSTR STR?249," bustles around the room"
	.GSTR STR?250,"You feel the wind changing direction"
	.GSTR STR?251,"The wind changes direction again"
	.GSTR STR?252,"A fresh wind blows from a new direction"
	.GSTR STR?253," moves its deadly gaze across the room"
	.GSTR STR?254," tries to lock eyes with yours"
	.GSTR STR?255," scans the room with its deadly gaze"
	.GSTR STR?256," almost stares you down"
	.GSTR STR?257," fixes its deadly gaze upon you"
	.GSTR STR?258,"'s eyes meet yours"
	.GSTR STR?259," locks its eyes onto your face"
	.GSTR STR?260,"'s gaze stops you cold"
	.GSTR STR?261,"making faces at you"
	.GSTR STR?262,"hurling insults at you"
	.GSTR STR?263,"reciting libelous rhymes about your personal life"
	.GSTR STR?264,"spreading rumors about you"
	.GSTR STR?265,"accusing you of shocking indiscretions"
	.GSTR STR?266,"taunting you"
	.GSTR STR?267," swings back and forth in its tree"
	.GSTR STR?268," pauses to think of another insult"
	.GSTR STR?269," dodges behind a tree trunk"
	.GSTR STR?270," stops to chuckle at its own cleverness"
	.GSTR STR?271," twists its body into an unflattering parody of your own"
	.GSTR STR?272," recites your nightly personal habits in excruciating detail"
	.GSTR STR?273," mirrors the expression on your face with infuriating accuracy"
	.GSTR STR?274," accuses your mother of shocking improprieties"
	.GSTR STR?275," reminds you how much weight you've gained lately, and where"
	.GSTR STR?276,"The bony fingers close tighter around your throat"
	.GSTR STR?277,"You gasp for breath as the skeleton throttles your neck"
	.GSTR STR?278,"The skeleton grins with menace as its fingers close tighter"
	.GSTR STR?279,"stepladder"
	.GSTR STR?280,"black cat"
	.GSTR STR?281,"giant number 13"
	.GSTR STR?282,"spinning umbrella"
	.GSTR STR?283," pirouettes across the chamber, grazing the mirror"
	.GSTR STR?284," yowls playfully, leaps high and rakes its claws across the mirror"
	.GSTR STR?285," studies itself in the mirror, frowns, and jabs at it angrily"
	.GSTR STR?286,"'s point nudges against the mirror"
	.GSTR STR?287," opens its legs wide, and steps right over you"
	.GSTR STR?288," does a somersault over your head"
	.GSTR STR?289," leaps over your head"
	.GSTR STR?290," marches back and forth in front of you"
	.GSTR STR?291," places itself directly in your path"
	.GSTR STR?292," slinks to and fro before you"
	.GSTR STR?293," points to itself, then at you"
	.GSTR STR?294," stares you right in the face"
	.GSTR STR?295," waves at you grimly"
	.GSTR STR?296," slowly opens, then snaps itself shut"
	.GSTR STR?297," snaps itself open, then slowly closes"
	.GSTR STR?298," opens itself as wide as possible"
	.GSTR STR?299," clumps around the passage"
	.GSTR STR?300," twirls on one leg"
	.GSTR STR?301," tries to step over you"
	.GSTR STR?302," races around the chamber"
	.GSTR STR?303," tries to cross your path"
	.GSTR STR?304," slinks along the edge of the passage"
	.GSTR STR?305," slides closer to you"
	.GSTR STR?306," does its best to keep your attention"
	.GSTR STR?307," tries to block the passage"
	.GSTR STR?308," whacks the wall trying to open itself"
	.GSTR STR?309," whirls towards the center of the passage"
	.GSTR STR?310," stops moving, then spins the other way"
	.GSTR STR?311,"brushes past"
	.GSTR STR?312,"is stalking"
	.GSTR STR?313,"circles around"
	.GSTR STR?314," sputters uselessly"
	.GSTR STR?315," emits a few feeble sparks"
	.GSTR STR?316," coughs impotently"
	.GSTR STR?317,"Yours for only "
	.GSTR STR?318,"A rare bargain at "
	.GSTR STR?319,"I'd part with it for "
	.GSTR STR?320,"For you, just "
	.GSTR STR?321,"This used one's worth "
	.GSTR STR?322,"Used, it's worth about "
	.GSTR STR?323,"A used one like this goes for "
	.GSTR STR?324,"The peace of the countryside is shattered"
	.GSTR STR?325,"Decrepit buildings close in on every side"
	.GSTR STR?326,"The road becomes noisy and crowded"
	.GSTR STR?327,"Clammy mist obscures your view of either end"
	.GSTR STR?328,"Your ears ring from the roar of water far below"
	.GSTR STR?329,"Both edges of the chasm are obscured in the clammy mist"
	.GSTR STR?330,"The deafening roar of water is giving you a headache"
	.GSTR STR?331,"Ah, yes! A "
	.GSTR STR?332,"That's a "
	.GSTR STR?333,"A "
	.GSTR STR?334,"Your basic "
	.GSTR STR?335,"Behold! A "
	.GSTR STR?336,"This is a "
	.GSTR STR?337," Begin using a preset character    "
	.GSTR STR?338," Select a preset character         "
	.GSTR STR?339," Randomly generate a new character "
	.GSTR STR?340," Create your own character         "
	.GSTR STR?341," Quit "
	.GSTR STR?342," dabs a bit more paint onto the canvas"
	.GSTR STR?343," eyes his work critically"
	.GSTR STR?344," touches up a spot on his painting"
	.GSTR STR?345," pauses to squint at his handiwork"
	.GSTR STR?346,"stumble blindly ahead"
	.GSTR STR?347,"inch forward one step at a time"
	.GSTR STR?348,"feel your way onward"
	.GSTR STR?349,"sniff"
	.GSTR STR?350,"laugh"
	.GSTR STR?351,"observe"
	.GSTR STR?352,"chuckle"
	.GSTR STR?353,"mutter"
	.GSTR STR?354,"You hear something move"
	.GSTR STR?355,"Something is moving around"
	.GSTR STR?356,"You hear a movement"
	.GSTR STR?357,"Something moves"
	.GSTR STR?358,"Welcome back"
	.GSTR STR?359,"Still alive? Impressive"
	.GSTR STR?360,"How nice of you to return"
	.GSTR STR?361,"You'll be back,"
	.GSTR STR?362,"Leaving so soon?"
	.GSTR STR?363,"Do drop in again,"
	.GSTR STR?364," divide once again"
	.GSTR STR?365," are still dividing"
	.GSTR STR?366," have divided once again"
	.GSTR STR?367," continue to divide"
	.GSTR STR?368," dusts off the items in "
	.GSTR STR?369," putters around behind "
	.GSTR STR?370," polishes the top of "
	.GSTR STR?371," leans against "
	.GSTR STR?372,"The bandits chuckle among themselves"
	.GSTR STR?373,"""Har!"" shouts a bandit, for no apparent reason"
	.GSTR STR?374,"One of the bandits winks at you"
	.GSTR STR?375,"eyeing you curiously"
	.GSTR STR?376,"keeping an eye on you"
	.GSTR STR?377,"watching every move you make"
	.GSTR STR?378,"Yow"
	.GSTR STR?379,"Ouch"
	.GSTR STR?380,"Oof"
	.GSTR STR?381," closes in with its pincers"
	.GSTR STR?382," gives you a nasty pinch"
	.GSTR STR?383,"'s pincers close in again"
	.GSTR STR?384," pinches you hard"
	.GSTR STR?385,"'s pincers barely miss your leg"
	.GSTR STR?386," misses you again, but just barely"
	.GSTR STR?387," feints sideways, pincers snapping"
	.GSTR STR?388," barely misses you again"
	.GSTR STR?389," snaps out with its pincers, just missing you"
	.GSTR STR?390," strikes out at you, but misses"
	.GSTR STR?391," poises itself for another strike"
	.GSTR STR?392," closes in with its sharp teeth"
	.GSTR STR?393," gives you a nasty bite"
	.GSTR STR?394,"'s teeth close in again"
	.GSTR STR?395," bites you hard"
	.GSTR STR?396,"'s teeth barely miss your ankle"
	.GSTR STR?397," feints to one side, teeth snapping"
	.GSTR STR?398," swipes out with its claws, just missing you"
	.GSTR STR?399," closes in with its sharp beak"
	.GSTR STR?400," gives you a nasty peck"
	.GSTR STR?401,"'s beak closes in again"
	.GSTR STR?402," pecks you hard"
	.GSTR STR?403,"'s beak barely misses your eye"
	.GSTR STR?404," feints to one side, eyes flashing"
	.GSTR STR?405," swipes out with its beak, just missing you"
	.GSTR STR?406," whispers an obscene secret in your ear"
	.GSTR STR?407," giggles insanely"
	.GSTR STR?408," darts around your head, just out of reach"
	.GSTR STR?409,"Giggling with glee"
	.GSTR STR?410,"Cackling with mischief"
	.GSTR STR?411,"Sniggering maliciously"
	.GSTR STR?412," tickles you in a sensitive place"
	.GSTR STR?413," pokes you where you ought not to be poked"
	.GSTR STR?414," infiltrates your naughty bits"
	.GSTR STR?415,"Boo"
	.GSTR STR?416,"Nyeah, nyeah"
	.GSTR STR?417,"Cootchy-cootchy-coo"
	.GSTR STR?418,"Woo-woo-woo"
	.GSTR STR?419,"Nyuk, nyuk, nyuk"
	.GSTR STR?420," closes in with its mandibles"
	.GSTR STR?421," gives you a nasty sting"
	.GSTR STR?422,"'s mandibles close in again"
	.GSTR STR?423," stings you hard"
	.GSTR STR?424," tries to grab you with its mandibles"
	.GSTR STR?425," feints to one side, mandibles ready"
	.GSTR STR?426," reaches out with its mandibles, just missing you"
	.GSTR STR?427," squirts vile ichors at you"
	.GSTR STR?428," gives you a nasty squirt"
	.GSTR STR?429,"'s squirt glands score a direct hit"
	.GSTR STR?430," squirts you again"
	.GSTR STR?431," tries to squirt you with vile ichors"
	.GSTR STR?432," poises itself for another squirt"
	.GSTR STR?433," feints to one side, squirt glands at the ready"
	.GSTR STR?434," squirts out again, just missing you"
	.GSTR STR?435," closes in with its fangs"
	.GSTR STR?436,"'s fangs close in again"
	.GSTR STR?437," strikes you hard"
	.GSTR STR?438," tries to impale you with its fangs"
	.GSTR STR?439," feints to one side, fangs bared"
	.GSTR STR?440," strikes out with its fangs, just missing you"
	.GSTR STR?441," closes in with its jaws"
	.GSTR STR?442," gives you a nasty snap"
	.GSTR STR?443,"'s jaws close in again"
	.GSTR STR?444," tries to snap you with its jaws"
	.GSTR STR?445," feints to one side, jaws snapping"
	.GSTR STR?446," strikes out with its jaws, just missing you"
	.GSTR STR?447," closes in with his ghostly blade"
	.GSTR STR?448," gives you a nasty cut"
	.GSTR STR?449,"'s blade closes in again"
	.GSTR STR?450," tries to slice you with his ghostly blade"
	.GSTR STR?451," feints to one side, blade swinging"
	.GSTR STR?452," strikes out with his blade, just missing you"
	.GSTR STR?453," poises himself for another strike"
	.GSTR STR?454," closes in with his spade"
	.GSTR STR?455,"'s spade closes in again"
	.GSTR STR?456," tries to brain you with his spade"
	.GSTR STR?457," feints to one side, spade swinging"
	.GSTR STR?458," strikes out with his spade, just missing you"
	.GSTR STR?459,"but miss"
	.GSTR STR?460,"missing by a hair"
	.GSTR STR?461,"nearly hitting it"
	.GSTR STR?462,"just barely missing"
	.GSTR STR?487," glances at "
	.GSTR STR?488,"There's nothing "
	.GSTR STR?489," at the moment.
"
	.GSTR STR?490,"The old woman"
	.GSTR STR?491," first.
"
	.GSTR STR?492,".""
"
	.GSTR STR?493," resting on the rim"
	.GSTR STR?494," lies half-hidden in "
	.GSTR STR?495," is visible in the "
	.GSTR STR?496,"caterpillar"
	.GSTR STR?497," lies forgotten in "
	.GSTR STR?498," lying in the dust."
	.GSTR STR?499,"Kerblam"
	.GSTR STR?500,"Whoosh"
	.GSTR STR?501," disappears into the "
	.GSTR STR?502,"NEW-EXIT?"
	.GSTR STR?503,"play horsey"
	.GSTR STR?504,"sprawling across the dust"
	.GSTR STR?505,"stick around"
	.GSTR STR?506,"abandoned and alone"
	.GSTR STR?507," lies at your feet."
	.GSTR STR?508,"UNDO"
	.GSTR STR?509," would respond.
"
	.GSTR STR?510,"ask about"
	.GSTR STR?511,"ASK CHARACTER ABOUT"
	.GSTR STR?512,"A hollow voice says, ""Fool!"""
	.GSTR STR?513,"any verbs"
	.GSTR STR?514,"enough nouns"
	.GSTR STR?515,". Bye!""
  She disappears with a wink.
"
	.GSTR STR?516,"reserved by the Implementors"
	.GSTR STR?517,"[Presumably, you mean "
	.GSTR STR?518,"open"
	.GSTR STR?519,"put down"
	.GSTR STR?520,"take off"
	.GSTR STR?521,"Snap"
	.GSTR STR?522,"snap"
	.GSTR STR?523,"s "
	.GSTR STR?524," "
	.GSTR STR?525,"You're broke.
"
	.GSTR STR?526,"financial"
	.GSTR STR?527,"Biting"
	.GSTR STR?528,"Blowing"
	.GSTR STR?529,"Cleaning"
	.GSTR STR?530,"Peering inside, you see "
	.GSTR STR?531,"closed"
	.GSTR STR?532,"safety"
	.GSTR STR?533,"You're right here.
"
	.GSTR STR?534," right here.
"
	.GSTR STR?535,"Kicking"
	.GSTR STR?536,"close"
	.GSTR STR?537,"surgeon"
	.GSTR STR?538,"veterinarian"
	.GSTR STR?539,"Trying to destroy"
	.GSTR STR?540,"locksmith"
	.GSTR STR?541,"remove"
	.GSTR STR?542,"Pulling on"
	.GSTR STR?543,"Pushing around"
	.GSTR STR?544,"Toying in this way with"
	.GSTR STR?545,"It's empty.
"
	.GSTR STR?546,"Fiddling with"
	.GSTR STR?547,"Paying respect to"
	.GSTR STR?548,"Shaking"
	.GSTR STR?549,"You're not wearing "
	.GSTR STR?550,"name things"
	.GSTR STR?551,"too complex"
	.GSTR STR?552,"too long"
	.GSTR STR?553," looks at you expectantly. "
	.GSTR STR?554,"Turning"
	.GSTR STR?555,"salesperson"
	.GSTR STR?556,"""You are too kind"
	.GSTR STR?557," and handing you "
	.GSTR STR?558,"ZOOM"
	.GSTR STR?559,"that way"
	.GSTR STR?560,"in this display mode"
	.GSTR STR?561,"PRIORITY"
	.GSTR STR?562,"Normal"
	.GSTR STR?563,"Enhanced"
	.GSTR STR?564,"Are you sure you want to "
	.GSTR STR?565,"RESTART"
	.GSTR STR?566,"RESTORE"
	.GSTR STR?567,"SAVE"
	.GSTR STR?568,"medical"
	.GSTR STR?569,"[Transcripting o"
	.GSTR STR?570,"begin"
	.GSTR STR?571,"end"
	.GSTR STR?572,"The Coconut of Quendor"
	.GSTR STR?573,"Copyright (C)1987 Infocom, Inc. All rights reserved."
	.GSTR STR?574,"$VERIFY"
	.GSTR STR?575,"[Combat monitor o"
	.GSTR STR?576,"plink"
	.GSTR STR?577," retreats into the "
	.GSTR STR?578," disappears in a spectral flash"
	.GSTR STR?579," retreats down the passageway, "
	.GSTR STR?580," lurks around the idol's maw"
	.GSTR STR?581," reappears from the "
	.GSTR STR?582,"Pop"
	.GSTR STR?583,"pop"
	.GSTR STR?584,"""Thank you for riding the Miznia Jungle Skyway"
	.GSTR STR?585,"the Skyway Adventure Emporium for a "
	.GSTR STR?586,"approaching from the south.
"
	.GSTR STR?587,". It probably won't last much longer.
"
	.GSTR STR?588,"a voice in the darkness"
	.GSTR STR?589,"how"
	.GSTR STR?590,"Pheebor"
	.GSTR STR?591,"Borphee"
	.GSTR STR?592," and disappears from view.
"
	.GSTR STR?593,"fade into the distance.
"
	.GSTR STR?594,"""Minx! Minx! Minx!""
"
	.GSTR STR?595,"violet"
	.GSTR STR?596," fills the air"
	.GSTR STR?597,". Unfortunately, "
	.GSTR STR?598,"! You can't help but "
	.GSTR STR?599,"close your eyes for a moment "
	.GSTR STR?600,"crimson"
	.GSTR STR?601," with a glare of annoyance.
"
	.GSTR STR?602,"Crash"
	.GSTR STR?603,"outside "
	.GSTR STR?604,"Thwack"
	.GSTR STR?605,"Bang"
	.GSTR STR?606,"Now"
	.GSTR STR?607,"cheerful-looking Implementor"
	.GSTR STR?608,"Plop"
	.GSTR STR?609,"tall, bearded Implementor"
	.GSTR STR?610,"mild-mannered Implementor"
	.GSTR STR?611,"goblet for you to take.
"
	.GSTR STR?612,"the reliquary behind his back. """
	.GSTR STR?613,"woo woo woo"
	.GSTR STR?614,"as you stand gawking at the landscape"
	.GSTR STR?615,"Poof"
	.GSTR STR?616,"plop"
	.GSTR STR?617," appears from the "
	.GSTR STR?618,"glow fades from orange to dull red.
"
	.GSTR STR?619," seem unwilling to approach you.
"
	.GSTR STR?620,"Your path is hopelessly blocked by "
	.GSTR STR?621,"n ominously cheerful rustling sound "
	.GSTR STR?622,"crunch"
	.GSTR STR?623,","" points out "
	.GSTR STR?624," gives you a puzzled frown"
	.GSTR STR?625,", but says nothing.
"
	.GSTR STR?626," doesn't seem to hear you.
"
	.GSTR STR?627,"very"
	.GSTR STR?628,". ""You got it!""
"
	.GSTR STR?629,"starin' at"
	.GSTR STR?630,"listenin' to"
	.GSTR STR?631," raises an eyebrow"
	.GSTR STR?632,"I've always been one to call a spade a spade"
	.GSTR STR?633,"I don't look at other people's mail"
	.GSTR STR?634,"Tidy little trinket, that"
	.GSTR STR?635,"Aluminized plastic. Festive, though"
	.GSTR STR?636,"Standard clerical issue"
	.GSTR STR?637,"Smallish; must be for a pony"
	.GSTR STR?638,"Antiques are big nowadays"
	.GSTR STR?639,"Phew! That thing wants a good airing"
	.GSTR STR?640,"That'll make some piano awfully happy"
	.GSTR STR?641,"A fair vintage"
	.GSTR STR?642,"A fair specimen"
	.GSTR STR?643,"Not the handsomest of mages"
	.GSTR STR?644,"Magick Shoppe in Gurth City"
	.GSTR STR?645,"weapon shop in Accardi"
	.GSTR STR?646,"boutique in Mizniaport"
	.GSTR STR?647," appears to have been neutralized"
	.GSTR STR?648,"My predecessor died suddenly"
	.GSTR STR?649,"Froon! A beautiful land, honorable to serve"
	.GSTR STR?650,"Ah, yes. Such a delicate shade of puce"
	.GSTR STR?651,"Mmm. Lovely mauve highlights"
	.GSTR STR?652,"Lavender! One of my favorite colors"
	.GSTR STR?653,"I preside over this humble diocese"
	.GSTR STR?654,"He disappeared a few weeks ago without trace"
	.GSTR STR?655,"Woe is us! Woe"
	.GSTR STR?656,"at the sound of your voice"
	.GSTR STR?657," to pay you much heed.
"
	.GSTR STR?658,"skulking in the corner"
	.GSTR STR?659,"scuttling across the dirt"
	.GSTR STR?660,"lurking among the reeds"
	.GSTR STR?661,"wafting amid the reeds"
	.GSTR STR?662,"lurking in the shadows"
	.GSTR STR?663,"squishing across the debris"
	.GSTR STR?664,"Splat"
	.GSTR STR?665,"slithering through the grass"
	.GSTR STR?666,"approach"
	.GSTR STR?667," seems ordinary enough.
"
	.GSTR STR?668,"out at you, barely missing your throat!
"
	.GSTR STR?669,"stalking through the undergrowth"
	.GSTR STR?670,"prowling between the trees"
	.GSTR STR?671,"resting beneath a tree"
	.GSTR STR?672,"feeds"
	.GSTR STR?673,"lurking amid the ruins"
	.GSTR STR?674,"crack"
	.GSTR STR?675,"skulking about the ruins"
	.GSTR STR?676,"love"
	.GSTR STR?677," lurking in the darkness nearby.
"
	.GSTR STR?678,"stalking the passageway"
	.GSTR STR?679,"waiting for you"
	.GSTR STR?680,"be holding"
	.GSTR STR?681,"You amble down the hill."
	.GSTR STR?682,"The hillside is too steep that way."
	.GSTR STR?683," can be seen not far to the north.
"
	.GSTR STR?684,"Tall reeds block your path."
	.GSTR STR?685,"You'd fall in the bay if you went that way."
	.GSTR STR?686,"Dank, fishy smells permeate this old wharf to its very bones."
	.GSTR STR?687,"hear the slurp of oily seawater against the piers"
	.GSTR STR?688,"Which way do you want to go out?"
	.GSTR STR?689,"You're already at the bottom of the stack."
	.GSTR STR?690,"You'd fall off the barrel if you went that way."
	.GSTR STR?691,"You carefully descend the stack."
	.GSTR STR?692,"You're up as high as you can go."
	.GSTR STR?693,"Rock walls block your path."
	.GSTR STR?694,"Christmas trees block your path."
	.GSTR STR?695,"Bonk"
	.GSTR STR?696,"Steep rock walls block your path."
	.GSTR STR?697,"you approach"
	.GSTR STR?698,", a cascade of lava hot on your heels"
	.GSTR STR?699,"You're in as far as you can go."
	.GSTR STR?700,"You'd tumble off the peak if you went that way."
	.GSTR STR?701,"Sheer cliff walls block your path."
	.GSTR STR?702,"You'd plummet into the sea if you went that way."
	.GSTR STR?703,"the sheer cliff wall"
	.GSTR STR?704,"You'd get soaked if you went that way."
	.GSTR STR?705,"The ocean smell is strong"
	.GSTR STR?706,"A thick forest blocks your path."
	.GSTR STR?707," noise makes you hesitate.
"
	.GSTR STR?708,"There aren't any stairs leading up from here."
	.GSTR STR?709,"You hurry down the steps."
	.GSTR STR?710,"There aren't any stairs leading down from here."
	.GSTR STR?711,"You descend the steps."
	.GSTR STR?712,"You climb down the steps."
	.GSTR STR?713,"You scramble down the steps."
	.GSTR STR?714,"Dense jungle blocks your path."
	.GSTR STR?715,"You're already at the bottom of the ladder."
	.GSTR STR?716,"You'd fall off the platform if you went that way."
	.GSTR STR?717,"get out of"
	.GSTR STR?718,"step past"
	.GSTR STR?719,"You'd plummet to your death if you went that way."
	.GSTR STR?720,"Another "
	.GSTR STR?721,"The rock wall blocks your path."
	.GSTR STR?722,"A cold, hard wall blocks your path."
	.GSTR STR?723,"A doorlike "
	.GSTR STR?724,"  A beam of sunlight "
	.GSTR STR?725," as far as you can see"
	.GSTR STR?726,"a sky black with thunderclouds"
	.GSTR STR?727," cowers at the field's edge.
  "
	.GSTR STR?728,"The ground is a bit too rough that way."
	.GSTR STR?729,"An impatient crowd of shoppers pushes you back."
	.GSTR STR?730,"outskirts of Gurth City"
	.GSTR STR?731,"edge of a vast forest"
	.GSTR STR?732,"You're not in the pool."
	.GSTR STR?733,"North"
	.GSTR STR?734,"South"
	.GSTR STR?735,"You'd plunge into the water if you went that way."
	.GSTR STR?736,"Rip"
	.GSTR STR?737,"Nothing but void lies that way."
	.GSTR STR?738,"ceding into the infinite "
	.GSTR STR?739,"An irresistible force holds you near the arch."
	.GSTR STR?740,"Whoever built this chamber forgot to provide any exits."
	.GSTR STR?741,"High castle walls block your path."
	.GSTR STR?742,"Ruins block your path."
	.GSTR STR?743,"Lush vegetation blocks your path."
	.GSTR STR?744,"The billboard"
	.GSTR STR?745,"in ruins"
	.GSTR STR?746,"Wham"
	.GSTR STR?747,"hook"
	.GSTR STR?748,"switch"
	.GSTR STR?749,"Click"
	.GSTR STR?750,"Smash"
	.GSTR STR?751,"mailbox on the bottle's label"
	.GSTR STR?752,"Chateau Blanc 877"
	.GSTR STR?753,"Wine"
	.GSTR STR?754,"splashes all over the place.
"
	.GSTR STR?755,"One of the stars"
	.GSTR STR?756,"The star"
	.GSTR STR?757," on the amulet "
	.GSTR STR?758," swirls and flourishes"
	.GSTR STR?759,"confusingly intertwined with "
	.GSTR STR?760,"Little can be seen "
	.GSTR STR?761,"board"
	.GSTR STR?762,"Children tug their parents' sleeves and point as you clamber "
	.GSTR STR?763,"You push your way "
	.GSTR STR?764,"over the gondola's edge"
	.GSTR STR?765,"Gondola"
	.GSTR STR?766,". There seems to be something "
	.GSTR STR?767," cannot be moved.
"
	.GSTR STR?768,"nonav"
	.GSTR STR?769,"As you reach towards the chest, you "
	.GSTR STR?770,"brass plate"
	.GSTR STR?771,"""Do Not Open This Chest.""
"
	.GSTR STR?772," to possess no physical substance.
"
	.GSTR STR?773,". On it you see "
	.GSTR STR?774," in a dizzy maelstrom of sound and motion"
	.GSTR STR?775,", barely missing its wide-eyed target"
	.GSTR STR?776,"Blit"
	.GSTR STR?777,"Sweat breaks out on your forehead as you "
	.GSTR STR?778,"guide the heavy burden over the "
	.GSTR STR?779," and safely down to the ground.
"
	.GSTR STR?780,"You hear a noise like a vacuum cleaner, then a satisfied slurp as "
	.GSTR STR?781,"But nothing seems to come of it; and "
	.GSTR STR?782,"not"
	.GSTR STR?783," can't be moved that way.
"
	.GSTR STR?784,"take out"
	.GSTR STR?785,"Slurp"
	.GSTR STR?786,"leave"
	.GSTR STR?787,"Such movement is meaningless now."
	.GSTR STR?788,"north and south into infinity"
	.GSTR STR?789,"An irresistible force keeps you near the arch."
	.GSTR STR?790,"Only void lies that way."
	.GSTR STR?791," bears a sinister knight."
	.GSTR STR?792," is lying across "
	.GSTR STR?793,"climb up into"
	.GSTR STR?794,"Creak"
	.GSTR STR?795," lies crushed beneath "
	.GSTR STR?796," in the steady wind.
"
	.GSTR STR?797,"City of Froon"
	.GSTR STR?798,"lid"
	.GSTR STR?799,"Breadbox"
	.GSTR STR?800," won't turn that way"
	.GSTR STR?801,"crank"
	.GSTR STR?802,"that"
	.GSTR STR?803,"six little pictures, cunningly painted: an eye, an ear, a nose, a mouth, a hand and a clock"
	.GSTR STR?804,"left"
	.GSTR STR?805,"right"
	.GSTR STR?806,"backs away from"
	.GSTR STR?807,"blinks at"
	.GSTR STR?808,"Splash"
	.GSTR STR?809,"Your mouth tingles with refreshment.
"
	.GSTR STR?810,"Vial"
	.GSTR STR?811,"You'd have to get "
	.GSTR STR?812,"Saddle"
	.GSTR STR?813," sweet and wholesome.
"
	.GSTR STR?814,"loosen a bit of"
	.GSTR STR?815,"Beachball"
	.GSTR STR?816,"Sploosh"
	.GSTR STR?817,"pick up"
	.GSTR STR?818,"me"
	.GSTR STR?819,","" he barks, shoving the ungainly vegetable back into place.
"
	.GSTR STR?820,"Thud"
	.GSTR STR?821,"The moss seems soft and pliant.
"
	.GSTR STR?822,"clunk"
	.GSTR STR?823,"opened"
	.GSTR STR?824,"The Wizard of Froon"
	.GSTR STR?825," you're wearing"
	.GSTR STR?826,"Ploop"
	.GSTR STR?827,"Gloop"
	.GSTR STR?828,"ploop"
	.GSTR STR?829,"slurp"
	.GSTR STR?830,"umbrella's handle"
	.GSTR STR?831,"chain"
	.GSTR STR?832,"at the sound"
	.GSTR STR?833,"seems to be something underneath"
	.GSTR STR?834,", but turn up nothing of interest.
"
	.GSTR STR?835," offers no good footholds.
"
	.GSTR STR?836,"the rug for a moment, but the smell quickly drives you "
	.GSTR STR?837,"Zap"
	.GSTR STR?838,"The word "
	.GSTR STR?839,"feel a moment of dizziness"
	.GSTR STR?840,"refreshment"
	.GSTR STR?841,"transcendental physics"
	.GSTR STR?842,"An inscription is carved upon the face of "
	.GSTR STR?843,"haven't studied any glyphs well enough to inscribe one yourself.
"
	.GSTR STR?844,"the iridescent surface of the dome"
	.GSTR STR?845,"gawk at"
	.GSTR STR?846,", but find nothing else of interest.
"
	.GSTR STR?847,"You fix your gaze deep within the crystal, "
	.GSTR STR?848,". This curious vision quickly fades.
"
	.GSTR STR?849,"23 July"
	.GSTR STR?850,"26 July"
	.GSTR STR?851,"2 August"
	.GSTR STR?852,"9 August"
	.GSTR STR?853,"13 August"
	.GSTR STR?854,"must"
	.GSTR STR?855,"Magic Equipment"
	.GSTR STR?856,"Burin"
	.GSTR STR?857,"Wastrel.
"
	.GSTR STR?858,"Potion"
	.GSTR STR?859,"top"
	.GSTR STR?860,"bottom"
	.GSTR STR?861,"
Do you want to "
	.GSTR STR?862,"highlight your selection.

Type [RETURN] to continue. >"
	.GSTR STR?863,"
Are you sure "
	.GSTR STR?864,"silly"
	.GSTR STR?865,"cast into the void"
	.GSTR STR?866,"address characters"
	.GSTR STR?867,"Beyond Zork"
	.GSTR STR?868,"marketing"
	.GSTR STR?869,"Zork"
	.GSTR STR?870,"Tossio"
	.GSTR STR?871,"N"
	.GSTR STR?872,"NE"
	.GSTR STR?873,"E"
	.GSTR STR?874,"SE"
	.GSTR STR?875,"S"
	.GSTR STR?876,"SW"
	.GSTR STR?877,"W"
	.GSTR STR?878,"NW"
	.GSTR STR?879,"Up"
	.GSTR STR?880,"Down"
	.GSTR STR?881,"In"
	.GSTR STR?882,"Out"
	.GSTR STR?883,"  "
	.GSTR STR?884,".
"
	.GSTR STR?885,".
  "
	.GSTR STR?886,"You see "
	.GSTR STR?887,", you see "
	.GSTR STR?888,"You can't "
	.GSTR STR?889,"You don't "
	.GSTR STR?890,"You hear "
	.GSTR STR?891,"You're already "
	.GSTR STR?892,"]
  "
	.GSTR STR?893,"You couldn't possibly "
	.GSTR STR?894,"The "
	.GSTR STR?895,"the "
	.GSTR STR?896,", and "
	.GSTR STR?897," into "
	.GSTR STR?898," with "
	.GSTR STR?899,"You "
	.GSTR STR?900," and "
	.GSTR STR?901,"Your "
	.GSTR STR?902," in "
	.GSTR STR?903," on "
	.GSTR STR?904," is "
	.GSTR STR?905," to "
	.GSTR STR?906," the "

	.ENDI
